#include "stdafx.h"
#include "base/string_number_convertions.h"
#include "modules/builtin/component_hotkey_id.h"
#include "modules/builtin/component_config.h"
#include "modules/process/component_wait_chain.h"
#include "modules/component_id.h"
#include "modules/window/utils/scoped_thread_attach.h"
#include "modules/window/app/window_app_utils.h"
#include "modules/window/app/properties/dlg_window_op.h"

struct WMInfo {
    TCHAR *m_pWMInfo;
    DWORD m_nMsg;
};

static WMInfo s_vWMInfoList[] = {
    { _T("ACM_ISPLAYING"), ACM_ISPLAYING },
    { _T("ACM_OPENA"), ACM_OPENA },
    { _T("ACM_OPENW"), ACM_OPENW },
    { _T("ACM_PLAY"), ACM_PLAY },
    { _T("ACM_STOP"), ACM_STOP },
    { _T("BCM_GETIDEALSIZE"), BCM_GETIDEALSIZE },
    { _T("BCM_GETIMAGELIST"), BCM_GETIMAGELIST },
    { _T("BCM_GETNOTE"), BCM_GETNOTE },
    { _T("BCM_GETNOTELENGTH"), BCM_GETNOTELENGTH },
    { _T("BCM_GETSPLITINFO"), BCM_GETSPLITINFO },
    { _T("BCM_GETTEXTMARGIN"), BCM_GETTEXTMARGIN },
    { _T("BCM_SETDROPDOWNSTATE"), BCM_SETDROPDOWNSTATE },
    { _T("BCM_SETIMAGELIST"), BCM_SETIMAGELIST },
    { _T("BCM_SETNOTE"), BCM_SETNOTE },
    { _T("BCM_SETSHIELD"), BCM_SETSHIELD },
    { _T("BCM_SETSPLITINFO"), BCM_SETSPLITINFO },
    { _T("BCM_SETTEXTMARGIN"), BCM_SETTEXTMARGIN },
    { _T("BM_CLICK"), BM_CLICK },
    { _T("BM_GETCHECK"), BM_GETCHECK },
    { _T("BM_GETIMAGE"), BM_GETIMAGE },
    { _T("BM_GETSTATE"), BM_GETSTATE },
    { _T("BM_SETCHECK"), BM_SETCHECK },
    { _T("BM_SETIMAGE"), BM_SETIMAGE },
    { _T("BM_SETSTATE"), BM_SETSTATE },
    { _T("BM_SETSTYLE"), BM_SETSTYLE },
    { _T("CB_ADDSTRING"), CB_ADDSTRING },
    { _T("CB_DELETESTRING"), CB_DELETESTRING },
    { _T("CB_DIR"), CB_DIR },
    { _T("CB_FINDSTRING"), CB_FINDSTRING },
    { _T("CB_FINDSTRINGEXACT"), CB_FINDSTRINGEXACT },
    { _T("CB_GETCOMBOBOXINFO"), CB_GETCOMBOBOXINFO },
    { _T("CB_GETCOUNT"), CB_GETCOUNT },
    { _T("CB_GETCUEBANNER"), CB_GETCUEBANNER },
    { _T("CB_GETCURSEL"), CB_GETCURSEL },
    { _T("CB_GETDROPPEDCONTROLRECT"), CB_GETDROPPEDCONTROLRECT },
    { _T("CB_GETDROPPEDSTATE"), CB_GETDROPPEDSTATE },
    { _T("CB_GETDROPPEDWIDTH"), CB_GETDROPPEDWIDTH },
    { _T("CB_GETEDITSEL"), CB_GETEDITSEL },
    { _T("CB_GETEXTENDEDUI"), CB_GETEXTENDEDUI },
    { _T("CB_GETHORIZONTALEXTENT"), CB_GETHORIZONTALEXTENT },
    { _T("CB_GETITEMDATA"), CB_GETITEMDATA },
    { _T("CB_GETITEMHEIGHT"), CB_GETITEMHEIGHT },
    { _T("CB_GETLBTEXT"), CB_GETLBTEXT },
    { _T("CB_GETLBTEXTLEN"), CB_GETLBTEXTLEN },
    { _T("CB_GETLOCALE"), CB_GETLOCALE },
    { _T("CB_GETMINVISIBLE"), CB_GETMINVISIBLE },
    { _T("CB_GETTOPINDEX"), CB_GETTOPINDEX },
    { _T("CB_INITSTORAGE"), CB_INITSTORAGE },
    { _T("CB_INSERTSTRING"), CB_INSERTSTRING },
    { _T("CB_LIMITTEXT"), CB_LIMITTEXT },
    { _T("CB_MULTIPLEADDSTRING"), 0x0163 }, // CB_MULTIPLEADDSTRING },
    { _T("CB_RESETCONTENT"), CB_RESETCONTENT },
    { _T("CB_SELECTSTRING"), CB_SELECTSTRING },
    { _T("CB_SETCUEBANNER"), CB_SETCUEBANNER },
    { _T("CB_SETCURSEL"), CB_SETCURSEL },
    { _T("CB_SETDROPPEDWIDTH"), CB_SETDROPPEDWIDTH },
    { _T("CB_SETEDITSEL"), CB_SETEDITSEL },
    { _T("CB_SETEXTENDEDUI"), CB_SETEXTENDEDUI },
    { _T("CB_SETHORIZONTALEXTENT"), CB_SETHORIZONTALEXTENT },
    { _T("CB_SETITEMDATA"), CB_SETITEMDATA },
    { _T("CB_SETITEMHEIGHT"), CB_SETITEMHEIGHT },
    { _T("CB_SETLOCALE"), CB_SETLOCALE },
    { _T("CB_SETMINVISIBLE"), CB_SETMINVISIBLE },
    { _T("CB_SETTOPINDEX"), CB_SETTOPINDEX },
    { _T("CB_SHOWDROPDOWN"), CB_SHOWDROPDOWN },
    { _T("CBEM_GETCOMBOCONTROL"), CBEM_GETCOMBOCONTROL },
    { _T("CBEM_GETEDITCONTROL"), CBEM_GETEDITCONTROL },
    { _T("CBEM_GETEXTENDEDSTYLE"), CBEM_GETEXTENDEDSTYLE },
    { _T("CBEM_GETIMAGELIST"), CBEM_GETIMAGELIST },
    { _T("CBEM_GETITEMA"), CBEM_GETITEMA },
    { _T("CBEM_GETITEMW"), CBEM_GETITEMW },
    { _T("CBEM_HASEDITCHANGED"), CBEM_HASEDITCHANGED },
    { _T("CBEM_INSERTITEMA"), CBEM_INSERTITEMA },
    { _T("CBEM_INSERTITEMW"), CBEM_INSERTITEMW },
    { _T("CBEM_SETEXSTYLE"), CBEM_SETEXSTYLE },
    { _T("CBEM_SETEXTENDEDSTYLE"), CBEM_SETEXTENDEDSTYLE },
    { _T("CBEM_SETIMAGELIST"), CBEM_SETIMAGELIST },
    { _T("CBEM_SETITEMA"), CBEM_SETITEMA },
    { _T("CBEM_SETITEMW"), CBEM_SETITEMW },
    { _T("CDM_GETFILEPATH"), CDM_GETFILEPATH },
    { _T("CDM_GETFOLDERIDLIST"), CDM_GETFOLDERIDLIST },
    { _T("CDM_GETFOLDERPATH"), CDM_GETFOLDERPATH },
    { _T("CDM_GETSPEC"), CDM_GETSPEC },
    { _T("CDM_HIDECONTROL"), CDM_HIDECONTROL },
    { _T("CDM_SETCONTROLTEXT"), CDM_SETCONTROLTEXT },
    { _T("CDM_SETDEFEXT"), CDM_SETDEFEXT },
    { _T("CCM_DPISCALE"), CCM_DPISCALE },
    { _T("CCM_GETCOLORSCHEME"), CCM_GETCOLORSCHEME },
    { _T("CCM_GETDROPTARGET"), CCM_GETDROPTARGET },
    { _T("CCM_GETUNICODEFORMAT"), CCM_GETUNICODEFORMAT },
    { _T("CCM_GETVERSION"), CCM_GETVERSION },
    { _T("CCM_SETBKCOLOR"), CCM_SETBKCOLOR },
    { _T("CCM_SETCOLORSCHEME"), CCM_SETCOLORSCHEME },
    { _T("CCM_SETNOTIFYWINDOW"), CCM_SETNOTIFYWINDOW },
    { _T("CCM_SETUNICODEFORMAT"), CCM_SETUNICODEFORMAT },
    { _T("CCM_SETVERSION"), CCM_SETVERSION },
    { _T("CCM_SETWINDOWTHEME"), CCM_SETWINDOWTHEME },
    { _T("DL_BEGINDRAG"), DL_BEGINDRAG },
    { _T("DL_CANCELDRAG"), DL_CANCELDRAG },
    { _T("DL_DRAGGING"), DL_DRAGGING },
    { _T("DL_DROPPED"), DL_DROPPED },
    { _T("DM_GETDEFID"), DM_GETDEFID },
    { _T("DM_REPOSITION"), DM_REPOSITION },
    { _T("DM_SETDEFID"), DM_SETDEFID },
    { _T("DTM_CLOSEMONTHCAL"), DTM_CLOSEMONTHCAL },
    { _T("DTM_GETDATETIMEPICKERINFO"), DTM_GETDATETIMEPICKERINFO },
    { _T("DTM_GETIDEALSIZE"), DTM_GETIDEALSIZE },
    { _T("DTM_GETMCCOLOR"), DTM_GETMCCOLOR },
    { _T("DTM_GETMCFONT"), DTM_GETMCFONT },
    { _T("DTM_GETMCSTYLE"), DTM_GETMCSTYLE },
    { _T("DTM_GETMONTHCAL"), DTM_GETMONTHCAL },
    { _T("DTM_GETRANGE"), DTM_GETRANGE },
    { _T("DTM_GETSYSTEMTIME"), DTM_GETSYSTEMTIME },
    { _T("DTM_SETFORMATA"), DTM_SETFORMATA },
    { _T("DTM_SETFORMATW"), DTM_SETFORMATW },
    { _T("DTM_SETMCCOLOR"), DTM_SETMCCOLOR },
    { _T("DTM_SETMCFONT"), DTM_SETMCFONT },
    { _T("DTM_SETMCSTYLE"), DTM_SETMCSTYLE },
    { _T("DTM_SETRANGE"), DTM_SETRANGE },
    { _T("DTM_SETSYSTEMTIME"), DTM_SETSYSTEMTIME },
    { _T("EM_AUTOURLDETECT"), EM_AUTOURLDETECT },
    { _T("EM_CANPASTE"), EM_CANPASTE },
    { _T("EM_CANREDO"), EM_CANREDO },
    { _T("EM_CANUNDO"), EM_CANUNDO },
    { _T("EM_CHARFROMPOS"), EM_CHARFROMPOS },
    { _T("EM_CONVPOSITION"), EM_CONVPOSITION },
    { _T("EM_DISPLAYBAND"), EM_DISPLAYBAND },
    { _T("EM_EMPTYUNDOBUFFER"), EM_EMPTYUNDOBUFFER },
    { _T("EM_EXGETSEL"), EM_EXGETSEL },
    { _T("EM_EXLIMITTEXT"), EM_EXLIMITTEXT },
    { _T("EM_EXLINEFROMCHAR"), EM_EXLINEFROMCHAR },
    { _T("EM_EXSETSEL"), EM_EXSETSEL },
    { _T("EM_FINDTEXT"), EM_FINDTEXT },
    { _T("EM_FINDTEXTW"), EM_FINDTEXTW },
    { _T("EM_FINDTEXTEX"), EM_FINDTEXTEX },
    { _T("EM_FINDTEXTEXW"), EM_FINDTEXTEXW },
    { _T("EM_FINDWORDBREAK"), EM_FINDWORDBREAK },
    { _T("EM_FMTLINES"), EM_FMTLINES },
    { _T("EM_FORMATRANGE"), EM_FORMATRANGE },
    { _T("EM_GETAUTOURLDETECT"), EM_GETAUTOURLDETECT },
    { _T("EM_GETBIDIOPTIONS"), EM_GETBIDIOPTIONS },
    { _T("EM_GETCHARFORMAT"), EM_GETCHARFORMAT },
    { _T("EM_GETCTFMODEBIAS"), EM_GETCTFMODEBIAS },
    { _T("EM_GETCTFOPENSTATUS"), EM_GETCTFOPENSTATUS },
    { _T("EM_GETCUEBANNER"), EM_GETCUEBANNER },
    { _T("EM_GETEDITSTYLE"), EM_GETEDITSTYLE },
    { _T("EM_GETEVENTMASK"), EM_GETEVENTMASK },
    { _T("EM_GETFIRSTVISIBLELINE"), EM_GETFIRSTVISIBLELINE },
    { _T("EM_GETHANDLE"), EM_GETHANDLE },
    { _T("EM_GETHILITE"), EM_GETHILITE },
    { _T("EM_GETHYPHENATEINFO"), EM_GETHYPHENATEINFO },
    { _T("EM_GETIMECOLOR"), EM_GETIMECOLOR },
    { _T("EM_GETIMECOMPMODE"), EM_GETIMECOMPMODE },
    { _T("EM_GETIMECOMPTEXT"), EM_GETIMECOMPTEXT },
    { _T("EM_GETIMEMODEBIAS"), EM_GETIMEMODEBIAS },
    { _T("EM_GETIMEOPTIONS"), EM_GETIMEOPTIONS },
    { _T("EM_GETIMEPROPERTY"), EM_GETIMEPROPERTY },
    { _T("EM_GETIMESTATUS"), EM_GETIMESTATUS },
    { _T("EM_GETLANGOPTIONS"), EM_GETLANGOPTIONS },
    { _T("EM_GETLIMITTEXT"), EM_GETLIMITTEXT },
    { _T("EM_GETLINE"), EM_GETLINE },
    { _T("EM_GETLINECOUNT"), EM_GETLINECOUNT },
    { _T("EM_GETMARGINS"), EM_GETMARGINS },
    { _T("EM_GETMODIFY"), EM_GETMODIFY },
    { _T("EM_GETOLEINTERFACE"), EM_GETOLEINTERFACE },
    { _T("EM_GETOPTIONS"), EM_GETOPTIONS },
    { _T("EM_GETPAGE"), EM_GETPAGE },
    { _T("EM_GETPAGEROTATE"), EM_GETPAGEROTATE },
    { _T("EM_GETPARAFORMAT"), EM_GETPARAFORMAT },
    { _T("EM_GETPASSWORDCHAR"), EM_GETPASSWORDCHAR },
    { _T("EM_GETPUNCTUATION"), EM_GETPUNCTUATION },
    { _T("EM_GETQUERYRTFOBJ"), EM_GETQUERYRTFOBJ },
    { _T("EM_GETRECT"), EM_GETRECT },
    { _T("EM_GETREDONAME"), EM_GETREDONAME },
    { _T("EM_GETSCROLLPOS"), EM_GETSCROLLPOS },
    { _T("EM_GETSEL"), EM_GETSEL },
    { _T("EM_GETSELTEXT"), EM_GETSELTEXT },
    { _T("EM_GETTEXTEX"), EM_GETTEXTEX },
    { _T("EM_GETTEXTLENGTHEX"), EM_GETTEXTLENGTHEX },
    { _T("EM_GETTEXTMODE"), EM_GETTEXTMODE },
    { _T("EM_GETTEXTRANGE"), EM_GETTEXTRANGE },
    { _T("EM_GETTHUMB"), EM_GETTHUMB },
    { _T("EM_GETTYPOGRAPHYOPTIONS"), EM_GETTYPOGRAPHYOPTIONS },
    { _T("EM_GETUNDONAME"), EM_GETUNDONAME },
    { _T("EM_GETVIEWKIND"), EM_GETVIEWKIND },
    { _T("EM_GETWORDBREAKPROC"), EM_GETWORDBREAKPROC },
    { _T("EM_GETWORDBREAKPROCEX"), EM_GETWORDBREAKPROCEX },
    { _T("EM_GETWORDWRAPMODE"), EM_GETWORDWRAPMODE },
    { _T("EM_GETZOOM"), EM_GETZOOM },
    { _T("EM_HIDEBALLOONTIP"), EM_HIDEBALLOONTIP },
    { _T("EM_HIDESELECTION"), EM_HIDESELECTION },
    { _T("EM_ISIME"), EM_ISIME },
    { _T("EM_LINEFROMCHAR"), EM_LINEFROMCHAR },
    { _T("EM_LINEINDEX"), EM_LINEINDEX },
    { _T("EM_LINELENGTH"), EM_LINELENGTH },
    { _T("EM_LINESCROLL"), EM_LINESCROLL },
    { _T("EM_OUTLINE"), EM_OUTLINE },
    { _T("EM_PASTESPECIAL"), EM_PASTESPECIAL },
    { _T("EM_POSFROMCHAR"), EM_POSFROMCHAR },
    { _T("EM_RECONVERSION"), EM_RECONVERSION },
    { _T("EM_REDO"), EM_REDO },
    { _T("EM_REPLACESEL"), EM_REPLACESEL },
    { _T("EM_REQUESTRESIZE"), EM_REQUESTRESIZE },
    { _T("EM_SCROLL"), EM_SCROLL },
    { _T("EM_SCROLLCARET"), EM_SCROLLCARET },
    { _T("EM_SELECTIONTYPE"), EM_SELECTIONTYPE },
    { _T("EM_SETBIDIOPTIONS"), EM_SETBIDIOPTIONS },
    { _T("EM_SETBKGNDCOLOR"), EM_SETBKGNDCOLOR },
    { _T("EM_SETCHARFORMAT"), EM_SETCHARFORMAT },
    { _T("EM_SETCTFMODEBIAS"), EM_SETCTFMODEBIAS },
    { _T("EM_SETCTFOPENSTATUS"), EM_SETCTFOPENSTATUS },
    { _T("EM_SETCUEBANNER"), EM_SETCUEBANNER },
    { _T("EM_SETEDITSTYLE"), EM_SETEDITSTYLE },
    { _T("EM_SETEVENTMASK"), EM_SETEVENTMASK },
    { _T("EM_SETFONTSIZE"), EM_SETFONTSIZE },
    { _T("EM_SETHANDLE"), EM_SETHANDLE },
    { _T("EM_SETHILITE"), EM_SETHILITE },
    { _T("EM_SETHYPHENATEINFO"), EM_SETHYPHENATEINFO },
    { _T("EM_SETIMECOLOR"), EM_SETIMECOLOR },
    { _T("EM_SETIMEMODEBIAS"), EM_SETIMEMODEBIAS },
    { _T("EM_SETIMEOPTIONS"), EM_SETIMEOPTIONS },
    { _T("EM_SETIMESTATUS"), EM_SETIMESTATUS },
    { _T("EM_SETLANGOPTIONS"), EM_SETLANGOPTIONS },
    { _T("EM_SETLIMITTEXT"), EM_SETLIMITTEXT },
    { _T("EM_SETMARGINS"), EM_SETMARGINS },
    { _T("EM_SETMODIFY"), EM_SETMODIFY },
    { _T("EM_SETOLECALLBACK"), EM_SETOLECALLBACK },
    { _T("EM_SETOPTIONS"), EM_SETOPTIONS },
    { _T("EM_SETPAGE"), EM_SETPAGE },
    { _T("EM_SETPAGEROTATE"), EM_SETPAGEROTATE },
    { _T("EM_SETPALETTE"), EM_SETPALETTE },
    { _T("EM_SETPARAFORMAT"), EM_SETPARAFORMAT },
    { _T("EM_SETPASSWORDCHAR"), EM_SETPASSWORDCHAR },
    { _T("EM_SETPUNCTUATION"), EM_SETPUNCTUATION },
    { _T("EM_SETQUERYRTFOBJ"), EM_SETQUERYRTFOBJ },
    { _T("EM_SETREADONLY"), EM_SETREADONLY },
    { _T("EM_SETRECT"), EM_SETRECT },
    { _T("EM_SETRECTNP"), EM_SETRECTNP },
    { _T("EM_SETSCROLLPOS"), EM_SETSCROLLPOS },
    { _T("EM_SETSEL"), EM_SETSEL },
    { _T("EM_SETTABSTOPS"), EM_SETTABSTOPS },
    { _T("EM_SETTARGETDEVICE"), EM_SETTARGETDEVICE },
    { _T("EM_SETTEXTEX"), EM_SETTEXTEX },
    { _T("EM_SETTEXTMODE"), EM_SETTEXTMODE },
    { _T("EM_SETTYPOGRAPHYOPTIONS"), EM_SETTYPOGRAPHYOPTIONS },
    { _T("EM_SETUNDOLIMIT"), EM_SETUNDOLIMIT },
    { _T("EM_SETVIEWKIND"), EM_SETVIEWKIND },
    { _T("EM_SETWORDBREAKPROC"), EM_SETWORDBREAKPROC },
    { _T("EM_SETWORDBREAKPROCEX"), EM_SETWORDBREAKPROCEX },
    { _T("EM_SETWORDWRAPMODE"), EM_SETWORDWRAPMODE },
    { _T("EM_SETZOOM"), EM_SETZOOM },
    { _T("EM_SHOWBALLOONTIP"), EM_SHOWBALLOONTIP },
    { _T("EM_SHOWSCROLLBAR"), EM_SHOWSCROLLBAR },
    { _T("EM_STOPGROUPTYPING"), EM_STOPGROUPTYPING },
    { _T("EM_STREAMIN"), EM_STREAMIN },
    { _T("EM_STREAMOUT"), EM_STREAMOUT },
    { _T("EM_UNDO"), EM_UNDO },
    //     { _T("FM_GETDRIVEINFOA"), FM_GETDRIVEINFOA },
    //     { _T("FM_GETDRIVEINFOW"), FM_GETDRIVEINFOW },
    //     { _T("FM_GETFILESELA"), FM_GETFILESELA },
    //     { _T("FM_GETFILESELW"), FM_GETFILESELW },
    //     { _T("FM_GETFILESELLFNA"), FM_GETFILESELLFNA },
    //     { _T("FM_GETFILESELLFNW"), FM_GETFILESELLFNW },
    //     { _T("FM_GETFOCUS"), FM_GETFOCUS },
    //     { _T("FM_GETSELCOUNT"), FM_GETSELCOUNT },
    //     { _T("FM_GETSELCOUNTLFN"), FM_GETSELCOUNTLFN },
    //     { _T("FM_REFRESH_WINDOWS"), FM_REFRESH_WINDOWS },
    //     { _T("FM_RELOAD_EXTENSIONS"), FM_RELOAD_EXTENSIONS },
    { _T("HDM_CREATEDRAGIMAGE"), HDM_CREATEDRAGIMAGE },
    { _T("HDM_CLEARFILTER"), HDM_CLEARFILTER },
    { _T("HDM_DELETEITEM"), HDM_DELETEITEM },
    { _T("HDM_EDITFILTER"), HDM_EDITFILTER },
    { _T("HDM_GETBITMAPMARGIN"), HDM_GETBITMAPMARGIN },
    { _T("HDM_GETFOCUSEDITEM"), HDM_GETFOCUSEDITEM },
    { _T("HDM_GETIMAGELIST"), HDM_GETIMAGELIST },
    { _T("HDM_GETITEMA"), HDM_GETITEMA },
    { _T("HDM_GETITEMW"), HDM_GETITEMW },
    { _T("HDM_GETITEMCOUNT"), HDM_GETITEMCOUNT },
    { _T("HDM_GETITEMDROPDOWNRECT"), HDM_GETITEMDROPDOWNRECT },
    { _T("HDM_GETITEMRECT"), HDM_GETITEMRECT },
    { _T("HDM_GETORDERARRAY"), HDM_GETORDERARRAY },
    { _T("HDM_GETOVERFLOWRECT"), HDM_GETOVERFLOWRECT },
    { _T("HDM_HITTEST"), HDM_HITTEST },
    { _T("HDM_INSERTITEMA"), HDM_INSERTITEMA },
    { _T("HDM_INSERTITEMW"), HDM_INSERTITEMW },
    { _T("HDM_LAYOUT"), HDM_LAYOUT },
    { _T("HDM_ORDERTOINDEX"), HDM_ORDERTOINDEX },
    { _T("HDM_SETBITMAPMARGIN"), HDM_SETBITMAPMARGIN },
    { _T("HDM_SETFILTERCHANGETIMEOUT"), HDM_SETFILTERCHANGETIMEOUT },
    { _T("HDM_SETFOCUSEDITEM"), HDM_SETFOCUSEDITEM },
    { _T("HDM_SETHOTDIVIDER"), HDM_SETHOTDIVIDER },
    { _T("HDM_SETIMAGELIST"), HDM_SETIMAGELIST },
    { _T("HDM_SETITEMA"), HDM_SETITEMA },
    { _T("HDM_SETITEMW"), HDM_SETITEMW },
    { _T("HDM_SETORDERARRAY"), HDM_SETORDERARRAY },
    { _T("HKM_GETHOTKEY"), HKM_GETHOTKEY },
    { _T("HKM_SETHOTKEY"), HKM_SETHOTKEY },
    { _T("HKM_SETRULES"), HKM_SETRULES },
    { _T("IPM_CLEARADDRESS"), IPM_CLEARADDRESS },
    { _T("IPM_GETADDRESS"), IPM_GETADDRESS },
    { _T("IPM_ISBLANK"), IPM_ISBLANK },
    { _T("IPM_SETADDRESS"), IPM_SETADDRESS },
    { _T("IPM_SETFOCUS"), IPM_SETFOCUS },
    { _T("IPM_SETRANGE"), IPM_SETRANGE },
    { _T("LB_ADDFILE"), LB_ADDFILE },
    { _T("LB_ADDSTRING"), LB_ADDSTRING },
    { _T("LB_DELETESTRING"), LB_DELETESTRING },
    { _T("LB_DIR"), LB_DIR },
    { _T("LB_FINDSTRING"), LB_FINDSTRING },
    { _T("LB_FINDSTRINGEXACT"), LB_FINDSTRINGEXACT },
    { _T("LB_GETANCHORINDEX"), LB_GETANCHORINDEX },
    { _T("LB_GETCARETINDEX"), LB_GETCARETINDEX },
    { _T("LB_GETCOUNT"), LB_GETCOUNT },
    { _T("LB_GETCURSEL"), LB_GETCURSEL },
    { _T("LB_GETHORIZONTALEXTENT"), LB_GETHORIZONTALEXTENT },
    { _T("LB_GETITEMDATA"), LB_GETITEMDATA },
    { _T("LB_GETITEMHEIGHT"), LB_GETITEMHEIGHT },
    { _T("LB_GETITEMRECT"), LB_GETITEMRECT },
    { _T("LB_GETLISTBOXINFO"), LB_GETLISTBOXINFO },
    { _T("LB_GETLOCALE"), LB_GETLOCALE },
    { _T("LB_GETSEL"), LB_GETSEL },
    { _T("LB_GETSELCOUNT"), LB_GETSELCOUNT },
    { _T("LB_GETSELITEMS"), LB_GETSELITEMS },
    { _T("LB_GETTEXT"), LB_GETTEXT },
    { _T("LB_GETTEXTLEN"), LB_GETTEXTLEN },
    { _T("LB_GETTOPINDEX"), LB_GETTOPINDEX },
    { _T("LB_INITSTORAGE"), LB_INITSTORAGE },
    { _T("LB_INSERTSTRING"), LB_INSERTSTRING },
    { _T("LB_ITEMFROMPOINT"), LB_ITEMFROMPOINT },
    { _T("LB_MULTIPLEADDSTRING"), 0x01B1 }, // LB_MULTIPLEADDSTRING },
    { _T("LB_RESETCONTENT"), LB_RESETCONTENT },
    { _T("LB_SELECTSTRING"), LB_SELECTSTRING },
    { _T("LB_SELITEMRANGE"), LB_SELITEMRANGE },
    { _T("LB_SELITEMRANGEEX"), LB_SELITEMRANGEEX },
    { _T("LB_SETANCHORINDEX"), LB_SETANCHORINDEX },
    { _T("LB_SETCARETINDEX"), LB_SETCARETINDEX },
    { _T("LB_SETCOLUMNWIDTH"), LB_SETCOLUMNWIDTH },
    { _T("LB_SETCOUNT"), LB_SETCOUNT },
    { _T("LB_SETCURSEL"), LB_SETCURSEL },
    { _T("LB_SETHORIZONTALEXTENT"), LB_SETHORIZONTALEXTENT },
    { _T("LB_SETITEMDATA"), LB_SETITEMDATA },
    { _T("LB_SETITEMHEIGHT"), LB_SETITEMHEIGHT },
    { _T("LB_SETLOCALE"), LB_SETLOCALE },
    { _T("LB_SETSEL"), LB_SETSEL },
    { _T("LB_SETTABSTOPS"), LB_SETTABSTOPS },
    { _T("LB_SETTOPINDEX"), LB_SETTOPINDEX },
    { _T("LM_GETIDEALHEIGHT"), LM_GETIDEALHEIGHT },
    { _T("LM_GETITEM"), LM_GETITEM },
    { _T("LM_HITTEST"), LM_HITTEST },
    { _T("LM_SETITEM"), LM_SETITEM },
    { _T("LVM_APPROXIMATEVIEWRECT"), LVM_APPROXIMATEVIEWRECT },
    { _T("LVM_ARRANGE"), LVM_ARRANGE },
    { _T("LVM_CANCELEDITLABEL"), LVM_CANCELEDITLABEL },
    { _T("LVM_CREATEDRAGIMAGE"), LVM_CREATEDRAGIMAGE },
    { _T("LVM_DELETEALLITEMS"), LVM_DELETEALLITEMS },
    { _T("LVM_DELETECOLUMN"), LVM_DELETECOLUMN },
    { _T("LVM_DELETEITEM"), LVM_DELETEITEM },
    { _T("LVM_EDITLABELA"), LVM_EDITLABELA },
    { _T("LVM_EDITLABELW"), LVM_EDITLABELW },
    { _T("LVM_ENABLEGROUPVIEW"), LVM_ENABLEGROUPVIEW },
    { _T("LVM_ENSUREVISIBLE"), LVM_ENSUREVISIBLE },
    { _T("LVM_FINDITEMA"), LVM_FINDITEMA },
    { _T("LVM_FINDITEMW"), LVM_FINDITEMW },
    { _T("LVM_GETBKCOLOR"), LVM_GETBKCOLOR },
    { _T("LVM_GETBKIMAGEA"), LVM_GETBKIMAGEA },
    { _T("LVM_GETBKIMAGEW"), LVM_GETBKIMAGEW },
    { _T("LVM_GETCALLBACKMASK"), LVM_GETCALLBACKMASK },
    { _T("LVM_GETCOLUMNA"), LVM_GETCOLUMNA },
    { _T("LVM_GETCOLUMNW"), LVM_GETCOLUMNW },
    { _T("LVM_GETCOLUMNORDERARRAY"), LVM_GETCOLUMNORDERARRAY },
    { _T("LVM_GETCOLUMNWIDTH"), LVM_GETCOLUMNWIDTH },
    { _T("LVM_GETCOUNTPERPAGE"), LVM_GETCOUNTPERPAGE },
    { _T("LVM_GETEDITCONTROL"), LVM_GETEDITCONTROL },
    { _T("LVM_GETEMPTYTEXT"), LVM_GETEMPTYTEXT },
    { _T("LVM_GETEXTENDEDLISTVIEWSTYLE"), LVM_GETEXTENDEDLISTVIEWSTYLE },
    { _T("LVM_GETFOCUSEDGROUP"), LVM_GETFOCUSEDGROUP },
    { _T("LVM_GETFOOTERINFO"), LVM_GETFOOTERINFO },
    { _T("LVM_GETFOOTERITEM"), LVM_GETFOOTERITEM },
    { _T("LVM_GETFOOTERITEMRECT"), LVM_GETFOOTERITEMRECT },
    { _T("LVM_GETFOOTERRECT"), LVM_GETFOOTERRECT },
    { _T("LVM_GETGROUPCOUNT"), LVM_GETGROUPCOUNT },
    { _T("LVM_GETGROUPINFO"), LVM_GETGROUPINFO },
    { _T("LVM_GETGROUPINFOBYINDEX"), LVM_GETGROUPINFOBYINDEX },
    { _T("LVM_GETGROUPMETRICS"), LVM_GETGROUPMETRICS },
    { _T("LVM_GETGROUPRECT"), LVM_GETGROUPRECT },
    { _T("LVM_GETGROUPSTATE"), LVM_GETGROUPSTATE },
    { _T("LVM_GETHEADER"), LVM_GETHEADER },
    { _T("LVM_GETHOTCURSOR"), LVM_GETHOTCURSOR },
    { _T("LVM_GETHOTITEM"), LVM_GETHOTITEM },
    { _T("LVM_GETHOVERTIME"), LVM_GETHOVERTIME },
    { _T("LVM_GETIMAGELIST"), LVM_GETIMAGELIST },
    { _T("LVM_GETINSERTMARK"), LVM_GETINSERTMARK },
    { _T("LVM_GETINSERTMARKCOLOR"), LVM_GETINSERTMARKCOLOR },
    { _T("LVM_GETINSERTMARKRECT"), LVM_GETINSERTMARKRECT },
    { _T("LVM_GETISEARCHSTRINGA"), LVM_GETISEARCHSTRINGA },
    { _T("LVM_GETISEARCHSTRINGW"), LVM_GETISEARCHSTRINGW },
    { _T("LVM_GETITEMA"), LVM_GETITEMA },
    { _T("LVM_GETITEMW"), LVM_GETITEMW },
    { _T("LVM_GETITEMCOUNT"), LVM_GETITEMCOUNT },
    { _T("LVM_GETITEMINDEXRECT"), LVM_GETITEMINDEXRECT },
    { _T("LVM_GETITEMPOSITION"), LVM_GETITEMPOSITION },
    { _T("LVM_GETITEMRECT"), LVM_GETITEMRECT },
    { _T("LVM_GETITEMSPACING"), LVM_GETITEMSPACING },
    { _T("LVM_GETITEMSTATE"), LVM_GETITEMSTATE },
    { _T("LVM_GETITEMTEXTA"), LVM_GETITEMTEXTA },
    { _T("LVM_GETITEMTEXTW"), LVM_GETITEMTEXTW },
    { _T("LVM_GETNEXTITEM"), LVM_GETNEXTITEM },
    { _T("LVM_GETNEXTITEMINDEX"), LVM_GETNEXTITEMINDEX },
    { _T("LVM_GETNUMBEROFWORKAREAS"), LVM_GETNUMBEROFWORKAREAS },
    { _T("LVM_GETORIGIN"), LVM_GETORIGIN },
    { _T("LVM_GETOUTLINECOLOR"), LVM_GETOUTLINECOLOR },
    { _T("LVM_GETSELECTEDCOLUMN"), LVM_GETSELECTEDCOLUMN },
    { _T("LVM_GETSELECTEDCOUNT"), LVM_GETSELECTEDCOUNT },
    { _T("LVM_GETSELECTIONMARK"), LVM_GETSELECTIONMARK },
    { _T("LVM_GETSTRINGWIDTHA"), LVM_GETSTRINGWIDTHA },
    { _T("LVM_GETSTRINGWIDTHW"), LVM_GETSTRINGWIDTHW },
    { _T("LVM_GETSUBITEMRECT"), LVM_GETSUBITEMRECT },
    { _T("LVM_GETTEXTBKCOLOR"), LVM_GETTEXTBKCOLOR },
    { _T("LVM_GETTEXTCOLOR"), LVM_GETTEXTCOLOR },
    { _T("LVM_GETTILEINFO"), LVM_GETTILEINFO },
    { _T("LVM_GETTILEVIEWINFO"), LVM_GETTILEVIEWINFO },
    { _T("LVM_GETTOOLTIPS"), LVM_GETTOOLTIPS },
    { _T("LVM_GETTOPINDEX"), LVM_GETTOPINDEX },
    { _T("LVM_GETVIEW"), LVM_GETVIEW },
    { _T("LVM_GETVIEWRECT"), LVM_GETVIEWRECT },
    { _T("LVM_GETWORKAREAS"), LVM_GETWORKAREAS },
    { _T("LVM_HASGROUP"), LVM_HASGROUP },
    { _T("LVM_HITTEST"), LVM_HITTEST },
    { _T("LVM_INSERTCOLUMNA"), LVM_INSERTCOLUMNA },
    { _T("LVM_INSERTCOLUMNW"), LVM_INSERTCOLUMNW },
    { _T("LVM_INSERTGROUP"), LVM_INSERTGROUP },
    { _T("LVM_INSERTGROUPSORTED"), LVM_INSERTGROUPSORTED },
    { _T("LVM_INSERTITEMA"), LVM_INSERTITEMA },
    { _T("LVM_INSERTITEMW"), LVM_INSERTITEMW },
    { _T("LVM_INSERTMARKHITTEST"), LVM_INSERTMARKHITTEST },
    { _T("LVM_ISGROUPVIEWENABLED"), LVM_ISGROUPVIEWENABLED },
    { _T("LVM_ISITEMVISIBLE"), LVM_ISITEMVISIBLE },
    { _T("LVM_MAPIDTOINDEX"), LVM_MAPIDTOINDEX },
    { _T("LVM_MAPINDEXTOID"), LVM_MAPINDEXTOID },
    { _T("LVM_MOVEGROUP"), LVM_MOVEGROUP },
    { _T("LVM_MOVEITEMTOGROUP"), LVM_MOVEITEMTOGROUP },
    { _T("LVM_REDRAWITEMS"), LVM_REDRAWITEMS },
    { _T("LVM_REMOVEALLGROUPS"), LVM_REMOVEALLGROUPS },
    { _T("LVM_REMOVEGROUP"), LVM_REMOVEGROUP },
    { _T("LVM_SCROLL"), LVM_SCROLL },
    { _T("LVM_SETBKCOLOR"), LVM_SETBKCOLOR },
    { _T("LVM_SETBKIMAGEA"), LVM_SETBKIMAGEA },
    { _T("LVM_SETBKIMAGEW"), LVM_SETBKIMAGEW },
    { _T("LVM_SETCALLBACKMASK"), LVM_SETCALLBACKMASK },
    { _T("LVM_SETCOLUMNA"), LVM_SETCOLUMNA },
    { _T("LVM_SETCOLUMNW"), LVM_SETCOLUMNW },
    { _T("LVM_SETCOLUMNORDERARRAY"), LVM_SETCOLUMNORDERARRAY },
    { _T("LVM_SETCOLUMNWIDTH"), LVM_SETCOLUMNWIDTH },
    { _T("LVM_SETEXTENDEDLISTVIEWSTYLE"), LVM_SETEXTENDEDLISTVIEWSTYLE },
    { _T("LVM_SETGROUPINFO"), LVM_SETGROUPINFO },
    { _T("LVM_SETGROUPMETRICS"), LVM_SETGROUPMETRICS },
    { _T("LVM_SETHOTCURSOR"), LVM_SETHOTCURSOR },
    { _T("LVM_SETHOTITEM"), LVM_SETHOTITEM },
    { _T("LVM_SETHOVERTIME"), LVM_SETHOVERTIME },
    { _T("LVM_SETICONSPACING"), LVM_SETICONSPACING },
    { _T("LVM_SETIMAGELIST"), LVM_SETIMAGELIST },
    { _T("LVM_SETINFOTIP"), LVM_SETINFOTIP },
    { _T("LVM_SETINSERTMARK"), LVM_SETINSERTMARK },
    { _T("LVM_SETINSERTMARKCOLOR"), LVM_SETINSERTMARKCOLOR },
    { _T("LVM_SETITEMA"), LVM_SETITEMA },
    { _T("LVM_SETITEMW"), LVM_SETITEMW },
    { _T("LVM_SETITEMCOUNT"), LVM_SETITEMCOUNT },
    { _T("LVM_SETITEMINDEXSTATE"), LVM_SETITEMINDEXSTATE },
    { _T("LVM_SETITEMPOSITION"), LVM_SETITEMPOSITION },
    { _T("LVM_SETITEMPOSITION32"), LVM_SETITEMPOSITION32 },
    { _T("LVM_SETITEMSTATE"), LVM_SETITEMSTATE },
    { _T("LVM_SETITEMTEXTA"), LVM_SETITEMTEXTA },
    { _T("LVM_SETITEMTEXTW"), LVM_SETITEMTEXTW },
    { _T("LVM_SETOUTLINECOLOR"), LVM_SETOUTLINECOLOR },
    { _T("LVM_SETSELECTEDCOLUMN"), LVM_SETSELECTEDCOLUMN },
    { _T("LVM_SETSELECTIONMARK"), LVM_SETSELECTIONMARK },
    { _T("LVM_SETTEXTBKCOLOR"), LVM_SETTEXTBKCOLOR },
    { _T("LVM_SETTEXTCOLOR"), LVM_SETTEXTCOLOR },
    { _T("LVM_SETTILEINFO"), LVM_SETTILEINFO },
    { _T("LVM_SETTILEVIEWINFO"), LVM_SETTILEVIEWINFO },
    { _T("LVM_SETTOOLTIPS"), LVM_SETTOOLTIPS },
    { _T("LVM_SETVIEW"), LVM_SETVIEW },
    { _T("LVM_SETWORKAREAS"), LVM_SETWORKAREAS },
    { _T("LVM_SORTGROUPS"), LVM_SORTGROUPS },
    { _T("LVM_SORTITEMS"), LVM_SORTITEMS },
    { _T("LVM_SORTITEMSEX"), LVM_SORTITEMSEX },
    { _T("LVM_SUBITEMHITTEST"), LVM_SUBITEMHITTEST },
    { _T("LVM_UPDATE"), LVM_UPDATE },
    { _T("MCM_GETCALENDARBORDER"), MCM_GETCALENDARBORDER },
    { _T("MCM_GETCALENDARCOUNT"), MCM_GETCALENDARCOUNT },
    { _T("MCM_GETCALENDARGRIDINFO"), MCM_GETCALENDARGRIDINFO },
    { _T("MCM_GETCALID"), MCM_GETCALID },
    { _T("MCM_GETCOLOR"), MCM_GETCOLOR },
    { _T("MCM_GETCURRENTVIEW"), MCM_GETCURRENTVIEW },
    { _T("MCM_GETCURSEL"), MCM_GETCURSEL },
    { _T("MCM_GETFIRSTDAYOFWEEK"), MCM_GETFIRSTDAYOFWEEK },
    { _T("MCM_GETMAXSELCOUNT"), MCM_GETMAXSELCOUNT },
    { _T("MCM_GETMAXTODAYWIDTH"), MCM_GETMAXTODAYWIDTH },
    { _T("MCM_GETMINREQRECT"), MCM_GETMINREQRECT },
    { _T("MCM_GETMONTHDELTA"), MCM_GETMONTHDELTA },
    { _T("MCM_GETMONTHRANGE"), MCM_GETMONTHRANGE },
    { _T("MCM_GETRANGE"), MCM_GETRANGE },
    { _T("MCM_GETSELRANGE"), MCM_GETSELRANGE },
    { _T("MCM_GETTODAY"), MCM_GETTODAY },
    { _T("MCM_HITTEST"), MCM_HITTEST },
    { _T("MCM_SETCALENDARBORDER"), MCM_SETCALENDARBORDER },
    { _T("MCM_SETCALID"), MCM_SETCALID },
    { _T("MCM_SETCOLOR"), MCM_SETCOLOR },
    { _T("MCM_SETCURRENTVIEW"), MCM_SETCURRENTVIEW },
    { _T("MCM_SETCURSEL"), MCM_SETCURSEL },
    { _T("MCM_SETDAYSTATE"), MCM_SETDAYSTATE },
    { _T("MCM_SETFIRSTDAYOFWEEK"), MCM_SETFIRSTDAYOFWEEK },
    { _T("MCM_SETMAXSELCOUNT"), MCM_SETMAXSELCOUNT },
    { _T("MCM_SETMONTHDELTA"), MCM_SETMONTHDELTA },
    { _T("MCM_SETRANGE"), MCM_SETRANGE },
    { _T("MCM_SETSELRANGE"), MCM_SETSELRANGE },
    { _T("MCM_SETTODAY"), MCM_SETTODAY },
    { _T("MCM_SIZERECTTOMIN"), MCM_SIZERECTTOMIN },
    { _T("NCM_DISPLAYERRORTIP"), NCM_DISPLAYERRORTIP },
    { _T("NCM_GETADDRESS"), NCM_GETADDRESS },
    { _T("NCM_GETALLOWTYPE"), NCM_GETALLOWTYPE },
    { _T("NCM_SETALLOWTYPE"), NCM_SETALLOWTYPE },
    { _T("PBM_DELTAPOS"), PBM_DELTAPOS },
    { _T("PBM_GETBARCOLOR"), PBM_GETBARCOLOR },
    { _T("PBM_GETBKCOLOR"), PBM_GETBKCOLOR },
    { _T("PBM_GETPOS"), PBM_GETPOS },
    { _T("PBM_GETRANGE"), PBM_GETRANGE },
    { _T("PBM_GETSTATE"), PBM_GETSTATE },
    { _T("PBM_GETSTEP"), PBM_GETSTEP },
    { _T("PBM_SETBARCOLOR"), PBM_SETBARCOLOR },
    { _T("PBM_SETMARQUEE"), PBM_SETMARQUEE },
    { _T("PBM_SETPOS"), PBM_SETPOS },
    { _T("PBM_SETRANGE"), PBM_SETRANGE },
    { _T("PBM_SETRANGE32"), PBM_SETRANGE32 },
    { _T("PBM_SETSTATE"), PBM_SETSTATE },
    { _T("PBM_SETSTEP"), PBM_SETSTEP },
    { _T("PBM_STEPIT"), PBM_STEPIT },
    { _T("PGM_FORWARDMOUSE"), PGM_FORWARDMOUSE },
    { _T("PGM_GETBKCOLOR"), PGM_GETBKCOLOR },
    { _T("PGM_GETBORDER"), PGM_GETBORDER },
    { _T("PGM_GETBUTTONSIZE"), PGM_GETBUTTONSIZE },
    { _T("PGM_GETBUTTONSTATE"), PGM_GETBUTTONSTATE },
    { _T("PGM_GETPOS"), PGM_GETPOS },
    { _T("PGM_RECALCSIZE"), PGM_RECALCSIZE },
    { _T("PGM_SETBKCOLOR"), PGM_SETBKCOLOR },
    { _T("PGM_SETBORDER"), PGM_SETBORDER },
    { _T("PGM_SETBUTTONSIZE"), PGM_SETBUTTONSIZE },
    { _T("PGM_SETCHILD"), PGM_SETCHILD },
    { _T("PGM_SETPOS"), PGM_SETPOS },
    { _T("PSM_ADDPAGE"), PSM_ADDPAGE },
    { _T("PSM_APPLY"), PSM_APPLY },
    { _T("PSM_CANCELTOCLOSE"), PSM_CANCELTOCLOSE },
    { _T("PSM_CHANGED"), PSM_CHANGED },
    { _T("PSM_ENABLEWIZBUTTONS"), PSM_ENABLEWIZBUTTONS },
    { _T("PSM_GETCURRENTPAGEHWND"), PSM_GETCURRENTPAGEHWND },
    { _T("PSM_GETTABCONTROL"), PSM_GETTABCONTROL },
    { _T("PSM_GETRESULT"), PSM_GETRESULT },
    { _T("PSM_HWNDTOINDEX"), PSM_HWNDTOINDEX },
    { _T("PSM_IDTOINDEX"), PSM_IDTOINDEX },
    { _T("PSM_INDEXTOHWND"), PSM_INDEXTOHWND },
    { _T("PSM_INDEXTOID"), PSM_INDEXTOID },
    { _T("PSM_INDEXTOPAGE"), PSM_INDEXTOPAGE },
    { _T("PSM_INSERTPAGE"), PSM_INSERTPAGE },
    { _T("PSM_ISDIALOGMESSAGE"), PSM_ISDIALOGMESSAGE },
    { _T("PSM_PAGETOINDEX"), PSM_PAGETOINDEX },
    { _T("PSM_PRESSBUTTON"), PSM_PRESSBUTTON },
    { _T("PSM_QUERYSIBLINGS"), PSM_QUERYSIBLINGS },
    { _T("PSM_REBOOTSYSTEM"), PSM_REBOOTSYSTEM },
    { _T("PSM_RECALCPAGESIZES"), PSM_RECALCPAGESIZES },
    { _T("PSM_REMOVEPAGE"), PSM_REMOVEPAGE },
    { _T("PSM_RESTARTWINDOWS"), PSM_RESTARTWINDOWS },
    { _T("PSM_SETBUTTONTEXTW"), PSM_SETBUTTONTEXTW },
    { _T("PSM_SETCURSEL"), PSM_SETCURSEL },
    { _T("PSM_SETCURSELID"), PSM_SETCURSELID },
    { _T("PSM_SETFINISHTEXTA"), PSM_SETFINISHTEXTA },
    { _T("PSM_SETFINISHTEXTW"), PSM_SETFINISHTEXTW },
    { _T("PSM_SETHEADERTITLEA"), PSM_SETHEADERTITLEA },
    { _T("PSM_SETHEADERTITLEW"), PSM_SETHEADERTITLEW },
    { _T("PSM_SETHEADERSUBTITLEA"), PSM_SETHEADERSUBTITLEA },
    { _T("PSM_SETHEADERSUBTITLEW"), PSM_SETHEADERSUBTITLEW },
    { _T("PSM_SETNEXTTEXTW"), PSM_SETNEXTTEXTW },
    { _T("PSM_SETTITLEA"), PSM_SETTITLEA },
    { _T("PSM_SETTITLEW"), PSM_SETTITLEW },
    { _T("PSM_SETWIZBUTTONS"), PSM_SETWIZBUTTONS },
    { _T("PSM_SHOWWIZBUTTONS"), PSM_SHOWWIZBUTTONS },
    { _T("PSM_UNCHANGED"), PSM_UNCHANGED },
    { _T("RB_BEGINDRAG"), RB_BEGINDRAG },
    { _T("RB_DELETEBAND"), RB_DELETEBAND },
    { _T("RB_DRAGMOVE"), RB_DRAGMOVE },
    { _T("RB_ENDDRAG"), RB_ENDDRAG },
    { _T("RB_GETBANDBORDERS"), RB_GETBANDBORDERS },
    { _T("RB_GETBANDCOUNT"), RB_GETBANDCOUNT },
    { _T("RB_GETBANDINFOA"), RB_GETBANDINFOA },
    { _T("RB_GETBANDINFOW"), RB_GETBANDINFOW },
    { _T("RB_GETBANDMARGINS"), RB_GETBANDMARGINS },
    { _T("RB_GETBARHEIGHT"), RB_GETBARHEIGHT },
    { _T("RB_GETBARINFO"), RB_GETBARINFO },
    { _T("RB_GETBKCOLOR"), RB_GETBKCOLOR },
    { _T("RB_GETEXTENDEDSTYLE"), RB_GETEXTENDEDSTYLE },
    { _T("RB_GETPALETTE"), RB_GETPALETTE },
    { _T("RB_GETRECT"), RB_GETRECT },
    { _T("RB_GETROWCOUNT"), RB_GETROWCOUNT },
    { _T("RB_GETROWHEIGHT"), RB_GETROWHEIGHT },
    { _T("RB_GETTEXTCOLOR"), RB_GETTEXTCOLOR },
    { _T("RB_GETTOOLTIPS"), RB_GETTOOLTIPS },
    { _T("RB_HITTEST"), RB_HITTEST },
    { _T("RB_IDTOINDEX"), RB_IDTOINDEX },
    { _T("RB_INSERTBANDA"), RB_INSERTBANDA },
    { _T("RB_INSERTBANDW"), RB_INSERTBANDW },
    { _T("RB_MAXIMIZEBAND"), RB_MAXIMIZEBAND },
    { _T("RB_MINIMIZEBAND"), RB_MINIMIZEBAND },
    { _T("RB_MOVEBAND"), RB_MOVEBAND },
    { _T("RB_PUSHCHEVRON"), RB_PUSHCHEVRON },
    { _T("RB_SETBANDINFOA"), RB_SETBANDINFOA },
    { _T("RB_SETBANDINFOW"), RB_SETBANDINFOW },
    { _T("RB_SETBANDWIDTH"), RB_SETBANDWIDTH },
    { _T("RB_SETBARINFO"), RB_SETBARINFO },
    { _T("RB_SETBKCOLOR"), RB_SETBKCOLOR },
    { _T("RB_SETEXTENDEDSTYLE"), RB_SETEXTENDEDSTYLE },
    { _T("RB_SETPALETTE"), RB_SETPALETTE },
    { _T("RB_SETPARENT"), RB_SETPARENT },
    { _T("RB_SETTEXTCOLOR"), RB_SETTEXTCOLOR },
    { _T("RB_SETTOOLTIPS"), RB_SETTOOLTIPS },
    { _T("RB_SHOWBAND"), RB_SHOWBAND },
    { _T("RB_SIZETORECT"), RB_SIZETORECT },
    { _T("SB_GETBORDERS"), SB_GETBORDERS },
    { _T("SB_GETICON"), SB_GETICON },
    { _T("SB_GETPARTS"), SB_GETPARTS },
    { _T("SB_GETRECT"), SB_GETRECT },
    { _T("SB_GETTEXTA"), SB_GETTEXTA },
    { _T("SB_GETTEXTW"), SB_GETTEXTW },
    { _T("SB_GETTEXTLENGTHA"), SB_GETTEXTLENGTHA },
    { _T("SB_GETTEXTLENGTHW"), SB_GETTEXTLENGTHW },
    { _T("SB_GETTIPTEXTA"), SB_GETTIPTEXTA },
    { _T("SB_GETTIPTEXTW"), SB_GETTIPTEXTW },
    { _T("SB_ISSIMPLE"), SB_ISSIMPLE },
    { _T("SB_SETICON"), SB_SETICON },
    { _T("SB_SETMINHEIGHT"), SB_SETMINHEIGHT },
    { _T("SB_SETPARTS"), SB_SETPARTS },
    { _T("SB_SETTEXTA"), SB_SETTEXTA },
    { _T("SB_SETTEXTW"), SB_SETTEXTW },
    { _T("SB_SETTIPTEXTA"), SB_SETTIPTEXTA },
    { _T("SB_SETTIPTEXTW"), SB_SETTIPTEXTW },
    { _T("SB_SIMPLE"), SB_SIMPLE },
    { _T("SBM_ENABLE_ARROWS"), SBM_ENABLE_ARROWS },
    { _T("SBM_GETPOS"), SBM_GETPOS },
    { _T("SBM_GETRANGE"), SBM_GETRANGE },
    { _T("SBM_GETSCROLLBARINFO"), SBM_GETSCROLLBARINFO },
    { _T("SBM_GETSCROLLINFO"), SBM_GETSCROLLINFO },
    { _T("SBM_SETPOS"), SBM_SETPOS },
    { _T("SBM_SETRANGE"), SBM_SETRANGE },
    { _T("SBM_SETRANGEREDRAW"), SBM_SETRANGEREDRAW },
    { _T("SBM_SETSCROLLINFO"), SBM_SETSCROLLINFO },
    { _T("STM_GETICON"), STM_GETICON },
    { _T("STM_GETIMAGE"), STM_GETIMAGE },
    { _T("STM_SETICON"), STM_SETICON },
    { _T("STM_SETIMAGE"), STM_SETIMAGE },
    { _T("TB_ADDBITMAP"), TB_ADDBITMAP },
    { _T("TB_ADDBUTTONSA"), TB_ADDBUTTONSA },
    { _T("TB_ADDBUTTONSW"), TB_ADDBUTTONSW },
    { _T("TB_ADDSTRINGA"), TB_ADDSTRINGA },
    { _T("TB_ADDSTRINGW"), TB_ADDSTRINGW },
    { _T("TB_AUTOSIZE"), TB_AUTOSIZE },
    { _T("TB_BUTTONCOUNT"), TB_BUTTONCOUNT },
    { _T("TB_BUTTONSTRUCTSIZE"), TB_BUTTONSTRUCTSIZE },
    { _T("TB_CHANGEBITMAP"), TB_CHANGEBITMAP },
    { _T("TB_CHECKBUTTON"), TB_CHECKBUTTON },
    { _T("TB_COMMANDTOINDEX"), TB_COMMANDTOINDEX },
    { _T("TB_CUSTOMIZE"), TB_CUSTOMIZE },
    { _T("TB_DELETEBUTTON"), TB_DELETEBUTTON },
    { _T("TB_ENABLEBUTTON"), TB_ENABLEBUTTON },
    { _T("TB_GETANCHORHIGHLIGHT"), TB_GETANCHORHIGHLIGHT },
    { _T("TB_GETBITMAP"), TB_GETBITMAP },
    { _T("TB_GETBITMAPFLAGS"), TB_GETBITMAPFLAGS },
    { _T("TB_GETBUTTON"), TB_GETBUTTON },
    { _T("TB_GETBUTTONINFOA"), TB_GETBUTTONINFOA },
    { _T("TB_GETBUTTONINFOW"), TB_GETBUTTONINFOW },
    { _T("TB_GETBUTTONSIZE"), TB_GETBUTTONSIZE },
    { _T("TB_GETBUTTONTEXTA"), TB_GETBUTTONTEXTA },
    { _T("TB_GETBUTTONTEXTW"), TB_GETBUTTONTEXTW },
    { _T("TB_GETDISABLEDIMAGELIST"), TB_GETDISABLEDIMAGELIST },
    { _T("TB_GETEXTENDEDSTYLE"), TB_GETEXTENDEDSTYLE },
    { _T("TB_GETHOTIMAGELIST"), TB_GETHOTIMAGELIST },
    { _T("TB_GETHOTITEM"), TB_GETHOTITEM },
    { _T("TB_GETIMAGELIST"), TB_GETIMAGELIST },
    { _T("TB_GETINSERTMARK"), TB_GETINSERTMARK },
    { _T("TB_GETINSERTMARKCOLOR"), TB_GETINSERTMARKCOLOR },
    { _T("TB_GETITEMRECT"), TB_GETITEMRECT },
    { _T("TB_GETMAXSIZE"), TB_GETMAXSIZE },
    { _T("TB_GETMETRICS"), TB_GETMETRICS },
    { _T("TB_GETOBJECT"), TB_GETOBJECT },
    { _T("TB_GETPADDING"), TB_GETPADDING },
    { _T("TB_GETPRESSEDIMAGELIST"), TB_GETPRESSEDIMAGELIST },
    { _T("TB_GETRECT"), TB_GETRECT },
    { _T("TB_GETROWS"), TB_GETROWS },
    { _T("TB_GETSTATE"), TB_GETSTATE },
    { _T("TB_GETSTRINGA"), TB_GETSTRINGA },
    { _T("TB_GETSTRINGW"), TB_GETSTRINGW },
    { _T("TB_GETSTYLE"), TB_GETSTYLE },
    { _T("TB_GETTEXTROWS"), TB_GETTEXTROWS },
    { _T("TB_GETTOOLTIPS"), TB_GETTOOLTIPS },
    { _T("TB_HIDEBUTTON"), TB_HIDEBUTTON },
    { _T("TB_HITTEST"), TB_HITTEST },
    { _T("TB_INDETERMINATE"), TB_INDETERMINATE },
    { _T("TB_INSERTBUTTONA"), TB_INSERTBUTTONA },
    { _T("TB_INSERTBUTTONW"), TB_INSERTBUTTONW },
    { _T("TB_INSERTMARKHITTEST"), TB_INSERTMARKHITTEST },
    { _T("TB_ISBUTTONCHECKED"), TB_ISBUTTONCHECKED },
    { _T("TB_ISBUTTONENABLED"), TB_ISBUTTONENABLED },
    { _T("TB_ISBUTTONHIDDEN"), TB_ISBUTTONHIDDEN },
    { _T("TB_ISBUTTONHIGHLIGHTED"), TB_ISBUTTONHIGHLIGHTED },
    { _T("TB_ISBUTTONINDETERMINATE"), TB_ISBUTTONINDETERMINATE },
    { _T("TB_ISBUTTONPRESSED"), TB_ISBUTTONPRESSED },
    { _T("TB_LOADIMAGES"), TB_LOADIMAGES },
    { _T("TB_MAPACCELERATORA"), TB_MAPACCELERATORA },
    { _T("TB_MAPACCELERATORW"), TB_MAPACCELERATORW },
    { _T("TB_MARKBUTTON"), TB_MARKBUTTON },
    { _T("TB_MOVEBUTTON"), TB_MOVEBUTTON },
    { _T("TB_PRESSBUTTON"), TB_PRESSBUTTON },
    { _T("TB_REPLACEBITMAP"), TB_REPLACEBITMAP },
    { _T("TB_SAVERESTOREA"), TB_SAVERESTOREA },
    { _T("TB_SAVERESTOREW"), TB_SAVERESTOREW },
    { _T("TB_SETANCHORHIGHLIGHT"), TB_SETANCHORHIGHLIGHT },
    { _T("TB_SETBITMAPSIZE"), TB_SETBITMAPSIZE },
    { _T("TB_SETBUTTONINFOA"), TB_SETBUTTONINFOA },
    { _T("TB_SETBUTTONINFOW"), TB_SETBUTTONINFOW },
    { _T("TB_SETBUTTONSIZE"), TB_SETBUTTONSIZE },
    { _T("TB_SETBUTTONWIDTH"), TB_SETBUTTONWIDTH },
    { _T("TB_SETCMDID"), TB_SETCMDID },
    { _T("TB_SETDISABLEDIMAGELIST"), TB_SETDISABLEDIMAGELIST },
    { _T("TB_SETDRAWTEXTFLAGS"), TB_SETDRAWTEXTFLAGS },
    { _T("TB_SETEXTENDEDSTYLE"), TB_SETEXTENDEDSTYLE },
    { _T("TB_SETHOTIMAGELIST"), TB_SETHOTIMAGELIST },
    { _T("TB_SETHOTITEM"), TB_SETHOTITEM },
    { _T("TB_SETIMAGELIST"), TB_SETIMAGELIST },
    { _T("TB_SETINDENT"), TB_SETINDENT },
    { _T("TB_SETINSERTMARK"), TB_SETINSERTMARK },
    { _T("TB_SETINSERTMARKCOLOR"), TB_SETINSERTMARKCOLOR },
    { _T("TB_SETMAXTEXTROWS"), TB_SETMAXTEXTROWS },
    { _T("TB_SETMETRICS"), TB_SETMETRICS },
    { _T("TB_SETPADDING"), TB_SETPADDING },
    { _T("TB_SETPARENT"), TB_SETPARENT },
    { _T("TB_SETPRESSEDIMAGELIST"), TB_SETPRESSEDIMAGELIST },
    { _T("TB_SETROWS"), TB_SETROWS },
    { _T("TB_SETSTATE"), TB_SETSTATE },
    { _T("TB_SETSTYLE"), TB_SETSTYLE },
    { _T("TB_SETTOOLTIPS"), TB_SETTOOLTIPS },
    { _T("TBM_CLEARSEL"), TBM_CLEARSEL },
    { _T("TBM_CLEARTICS"), TBM_CLEARTICS },
    { _T("TBM_GETBUDDY"), TBM_GETBUDDY },
    { _T("TBM_GETCHANNELRECT"), TBM_GETCHANNELRECT },
    { _T("TBM_GETLINESIZE"), TBM_GETLINESIZE },
    { _T("TBM_GETNUMTICS"), TBM_GETNUMTICS },
    { _T("TBM_GETPAGESIZE"), TBM_GETPAGESIZE },
    { _T("TBM_GETPOS"), TBM_GETPOS },
    { _T("TBM_GETPTICS"), TBM_GETPTICS },
    { _T("TBM_GETRANGEMAX"), TBM_GETRANGEMAX },
    { _T("TBM_GETRANGEMIN"), TBM_GETRANGEMIN },
    { _T("TBM_GETSELEND"), TBM_GETSELEND },
    { _T("TBM_GETSELSTART"), TBM_GETSELSTART },
    { _T("TBM_GETTHUMBLENGTH"), TBM_GETTHUMBLENGTH },
    { _T("TBM_GETTHUMBRECT"), TBM_GETTHUMBRECT },
    { _T("TBM_GETTIC"), TBM_GETTIC },
    { _T("TBM_GETTICPOS"), TBM_GETTICPOS },
    { _T("TBM_GETTOOLTIPS"), TBM_GETTOOLTIPS },
    { _T("TBM_SETBUDDY"), TBM_SETBUDDY },
    { _T("TBM_SETLINESIZE"), TBM_SETLINESIZE },
    { _T("TBM_SETPAGESIZE"), TBM_SETPAGESIZE },
    { _T("TBM_SETPOS"), TBM_SETPOS },
    { _T("TBM_SETRANGE"), TBM_SETRANGE },
    { _T("TBM_SETRANGEMAX"), TBM_SETRANGEMAX },
    { _T("TBM_SETRANGEMIN"), TBM_SETRANGEMIN },
    { _T("TBM_SETSEL"), TBM_SETSEL },
    { _T("TBM_SETSELEND"), TBM_SETSELEND },
    { _T("TBM_SETSELSTART"), TBM_SETSELSTART },
    { _T("TBM_SETTHUMBLENGTH"), TBM_SETTHUMBLENGTH },
    { _T("TBM_SETTIC"), TBM_SETTIC },
    { _T("TBM_SETTICFREQ"), TBM_SETTICFREQ },
    { _T("TBM_SETTIPSIDE"), TBM_SETTIPSIDE },
    { _T("TBM_SETTOOLTIPS"), TBM_SETTOOLTIPS },
    { _T("TCM_ADJUSTRECT"), TCM_ADJUSTRECT },
    { _T("TCM_DELETEALLITEMS"), TCM_DELETEALLITEMS },
    { _T("TCM_DELETEITEM"), TCM_DELETEITEM },
    { _T("TCM_DESELECTALL"), TCM_DESELECTALL },
    { _T("TCM_GETCURFOCUS"), TCM_GETCURFOCUS },
    { _T("TCM_GETCURSEL"), TCM_GETCURSEL },
    { _T("TCM_GETEXTENDEDSTYLE"), TCM_GETEXTENDEDSTYLE },
    { _T("TCM_GETIMAGELIST"), TCM_GETIMAGELIST },
    { _T("TCM_GETITEMA"), TCM_GETITEMA },
    { _T("TCM_GETITEMW"), TCM_GETITEMW },
    { _T("TCM_GETITEMCOUNT"), TCM_GETITEMCOUNT },
    { _T("TCM_GETITEMRECT"), TCM_GETITEMRECT },
    { _T("TCM_GETROWCOUNT"), TCM_GETROWCOUNT },
    { _T("TCM_GETTOOLTIPS"), TCM_GETTOOLTIPS },
    { _T("TCM_HIGHLIGHTITEM"), TCM_HIGHLIGHTITEM },
    { _T("TCM_HITTEST"), TCM_HITTEST },
    { _T("TCM_INSERTITEMA"), TCM_INSERTITEMA },
    { _T("TCM_INSERTITEMW"), TCM_INSERTITEMW },
    { _T("TCM_REMOVEIMAGE"), TCM_REMOVEIMAGE },
    { _T("TCM_SETCURFOCUS"), TCM_SETCURFOCUS },
    { _T("TCM_SETCURSEL"), TCM_SETCURSEL },
    { _T("TCM_SETEXTENDEDSTYLE"), TCM_SETEXTENDEDSTYLE },
    { _T("TCM_SETIMAGELIST"), TCM_SETIMAGELIST },
    { _T("TCM_SETITEMA"), TCM_SETITEMA },
    { _T("TCM_SETITEMW"), TCM_SETITEMW },
    { _T("TCM_SETITEMEXTRA"), TCM_SETITEMEXTRA },
    { _T("TCM_SETITEMSIZE"), TCM_SETITEMSIZE },
    { _T("TCM_SETMINTABWIDTH"), TCM_SETMINTABWIDTH },
    { _T("TCM_SETPADDING"), TCM_SETPADDING },
    { _T("TCM_SETTOOLTIPS"), TCM_SETTOOLTIPS },
    { _T("TTM_ACTIVATE"), TTM_ACTIVATE },
    { _T("TTM_ADDTOOLA"), TTM_ADDTOOLA },
    { _T("TTM_ADDTOOLW"), TTM_ADDTOOLW },
    { _T("TTM_ADJUSTRECT"), TTM_ADJUSTRECT },
    { _T("TTM_DELTOOLA"), TTM_DELTOOLA },
    { _T("TTM_DELTOOLW"), TTM_DELTOOLW },
    { _T("TTM_ENUMTOOLSA"), TTM_ENUMTOOLSA },
    { _T("TTM_ENUMTOOLSW"), TTM_ENUMTOOLSW },
    { _T("TTM_GETBUBBLESIZE"), TTM_GETBUBBLESIZE },
    { _T("TTM_GETCURRENTTOOLA"), TTM_GETCURRENTTOOLA },
    { _T("TTM_GETCURRENTTOOLW"), TTM_GETCURRENTTOOLW },
    { _T("TTM_GETDELAYTIME"), TTM_GETDELAYTIME },
    { _T("TTM_GETMARGIN"), TTM_GETMARGIN },
    { _T("TTM_GETMAXTIPWIDTH"), TTM_GETMAXTIPWIDTH },
    { _T("TTM_GETTEXTA"), TTM_GETTEXTA },
    { _T("TTM_GETTEXTW"), TTM_GETTEXTW },
    { _T("TTM_GETTIPBKCOLOR"), TTM_GETTIPBKCOLOR },
    { _T("TTM_GETTIPTEXTCOLOR"), TTM_GETTIPTEXTCOLOR },
    { _T("TTM_GETTITLE"), TTM_GETTITLE },
    { _T("TTM_GETTOOLCOUNT"), TTM_GETTOOLCOUNT },
    { _T("TTM_GETTOOLINFOA"), TTM_GETTOOLINFOA },
    { _T("TTM_GETTOOLINFOW"), TTM_GETTOOLINFOW },
    { _T("TTM_HITTESTA"), TTM_HITTESTA },
    { _T("TTM_HITTESTW"), TTM_HITTESTW },
    { _T("TTM_NEWTOOLRECTA"), TTM_NEWTOOLRECTA },
    { _T("TTM_NEWTOOLRECTW"), TTM_NEWTOOLRECTW },
    { _T("TTM_POP"), TTM_POP },
    { _T("TTM_POPUP"), TTM_POPUP },
    { _T("TTM_RELAYEVENT"), TTM_RELAYEVENT },
    { _T("TTM_SETDELAYTIME"), TTM_SETDELAYTIME },
    { _T("TTM_SETMARGIN"), TTM_SETMARGIN },
    { _T("TTM_SETMAXTIPWIDTH"), TTM_SETMAXTIPWIDTH },
    { _T("TTM_SETTIPBKCOLOR"), TTM_SETTIPBKCOLOR },
    { _T("TTM_SETTIPTEXTCOLOR"), TTM_SETTIPTEXTCOLOR },
    { _T("TTM_SETTITLEA"), TTM_SETTITLEA },
    { _T("TTM_SETTITLEW"), TTM_SETTITLEW },
    { _T("TTM_SETTOOLINFOA"), TTM_SETTOOLINFOA },
    { _T("TTM_SETTOOLINFOW"), TTM_SETTOOLINFOW },
    { _T("TTM_TRACKACTIVATE"), TTM_TRACKACTIVATE },
    { _T("TTM_TRACKPOSITION"), TTM_TRACKPOSITION },
    { _T("TTM_UPDATE"), TTM_UPDATE },
    { _T("TTM_UPDATETIPTEXTA"), TTM_UPDATETIPTEXTA },
    { _T("TTM_UPDATETIPTEXTW"), TTM_UPDATETIPTEXTW },
    { _T("TTM_WINDOWFROMPOINT"), TTM_WINDOWFROMPOINT },
    { _T("TVM_CREATEDRAGIMAGE"), TVM_CREATEDRAGIMAGE },
    { _T("TVM_DELETEITEM"), TVM_DELETEITEM },
    { _T("TVM_EDITLABELA"), TVM_EDITLABELA },
    { _T("TVM_EDITLABELW"), TVM_EDITLABELW },
    { _T("TVM_ENDEDITLABELNOW"), TVM_ENDEDITLABELNOW },
    { _T("TVM_ENSUREVISIBLE"), TVM_ENSUREVISIBLE },
    { _T("TVM_EXPAND"), TVM_EXPAND },
    { _T("TVM_GETBKCOLOR"), TVM_GETBKCOLOR },
    { _T("TVM_GETCOUNT"), TVM_GETCOUNT },
    { _T("TVM_GETEDITCONTROL"), TVM_GETEDITCONTROL },
    { _T("TVM_GETEXTENDEDSTYLE"), TVM_GETEXTENDEDSTYLE },
    { _T("TVM_GETIMAGELIST"), TVM_GETIMAGELIST },
    { _T("TVM_GETINDENT"), TVM_GETINDENT },
    { _T("TVM_GETINSERTMARKCOLOR"), TVM_GETINSERTMARKCOLOR },
    { _T("TVM_GETISEARCHSTRINGA"), TVM_GETISEARCHSTRINGA },
    { _T("TVM_GETISEARCHSTRINGW"), TVM_GETISEARCHSTRINGW },
    { _T("TVM_GETITEMA"), TVM_GETITEMA },
    { _T("TVM_GETITEMW"), TVM_GETITEMW },
    { _T("TVM_GETITEMHEIGHT"), TVM_GETITEMHEIGHT },
    { _T("TVM_GETITEMPARTRECT"), TVM_GETITEMPARTRECT },
    { _T("TVM_GETITEMRECT"), TVM_GETITEMRECT },
    { _T("TVM_GETITEMSTATE"), TVM_GETITEMSTATE },
    { _T("TVM_GETLINECOLOR"), TVM_GETLINECOLOR },
    { _T("TVM_GETNEXTITEM"), TVM_GETNEXTITEM },
    { _T("TVM_GETSCROLLTIME"), TVM_GETSCROLLTIME },
    { _T("TVM_GETSELECTEDCOUNT"), TVM_GETSELECTEDCOUNT },
    { _T("TVM_GETTEXTCOLOR"), TVM_GETTEXTCOLOR },
    { _T("TVM_GETTOOLTIPS"), TVM_GETTOOLTIPS },
    { _T("TVM_GETVISIBLECOUNT"), TVM_GETVISIBLECOUNT },
    { _T("TVM_HITTEST"), TVM_HITTEST },
    { _T("TVM_INSERTITEMA"), TVM_INSERTITEMA },
    { _T("TVM_INSERTITEMW"), TVM_INSERTITEMW },
    { _T("TVM_MAPACCIDTOHTREEITEM"), TVM_MAPACCIDTOHTREEITEM },
    { _T("TVM_MAPHTREEITEMTOACCID"), TVM_MAPHTREEITEMTOACCID },
    { _T("TVM_SELECTITEM"), TVM_SELECTITEM },
    { _T("TVM_SETAUTOSCROLLINFO"), TVM_SETAUTOSCROLLINFO },
    { _T("TVM_SETBKCOLOR"), TVM_SETBKCOLOR },
    { _T("TVM_SETEXTENDEDSTYLE"), TVM_SETEXTENDEDSTYLE },
    { _T("TVM_SETIMAGELIST"), TVM_SETIMAGELIST },
    { _T("TVM_SETINDENT"), TVM_SETINDENT },
    { _T("TVM_SETINSERTMARK"), TVM_SETINSERTMARK },
    { _T("TVM_SETINSERTMARKCOLOR"), TVM_SETINSERTMARKCOLOR },
    { _T("TVM_SETITEMA"), TVM_SETITEMA },
    { _T("TVM_SETITEMW"), TVM_SETITEMW },
    { _T("TVM_SETITEMHEIGHT"), TVM_SETITEMHEIGHT },
    { _T("TVM_SETLINECOLOR"), TVM_SETLINECOLOR },
    { _T("TVM_SETSCROLLTIME"), TVM_SETSCROLLTIME },
    { _T("TVM_SETTEXTCOLOR"), TVM_SETTEXTCOLOR },
    { _T("TVM_SETTOOLTIPS"), TVM_SETTOOLTIPS },
    { _T("TVM_SHOWINFOTIP"), TVM_SHOWINFOTIP },
    { _T("TVM_SORTCHILDREN"), TVM_SORTCHILDREN },
    { _T("TVM_SORTCHILDRENCB"), TVM_SORTCHILDRENCB },
    { _T("UDM_GETACCEL"), UDM_GETACCEL },
    { _T("UDM_GETBASE"), UDM_GETBASE },
    { _T("UDM_GETBUDDY"), UDM_GETBUDDY },
    { _T("UDM_GETPOS"), UDM_GETPOS },
    { _T("UDM_GETPOS32"), UDM_GETPOS32 },
    { _T("UDM_GETRANGE"), UDM_GETRANGE },
    { _T("UDM_GETRANGE32"), UDM_GETRANGE32 },
    { _T("UDM_SETACCEL"), UDM_SETACCEL },
    { _T("UDM_SETBASE"), UDM_SETBASE },
    { _T("UDM_SETBUDDY"), UDM_SETBUDDY },
    { _T("UDM_SETPOS"), UDM_SETPOS },
    { _T("UDM_SETPOS32"), UDM_SETPOS32 },
    { _T("UDM_SETRANGE"), UDM_SETRANGE },
    { _T("UDM_SETRANGE32"), UDM_SETRANGE32 },
    { _T("WM_ACTIVATE"), WM_ACTIVATE },
    { _T("WM_ACTIVATEAPP"), WM_ACTIVATEAPP },
    { _T("WM_ACTIVATETOPLEVEL"), 0x036E }, // WM_ACTIVATETOPLEVEL
    { _T("WM_APPCOMMAND"), WM_APPCOMMAND },
    { _T("WM_ASKCBFORMATNAME"), WM_ASKCBFORMATNAME },
    { _T("WM_CANCELJOURNAL"), WM_CANCELJOURNAL },
    { _T("WM_CANCELMODE"), WM_CANCELMODE },
    { _T("WM_CAPTURECHANGED"), WM_CAPTURECHANGED },
    { _T("WM_CHANGECBCHAIN"), WM_CHANGECBCHAIN },
    { _T("WM_CHANGEUISTATE"), WM_CHANGEUISTATE },
    { _T("WM_CHAR"), WM_CHAR },
    { _T("WM_CHARTOITEM"), WM_CHARTOITEM },
    { _T("WM_CHILDACTIVATE"), WM_CHILDACTIVATE },
    { _T("WM_CHOOSEFONT_GETLOGFONT"), WM_CHOOSEFONT_GETLOGFONT },
    { _T("WM_CHOOSEFONT_SETFLAGS"), WM_CHOOSEFONT_SETFLAGS },
    { _T("WM_CHOOSEFONT_SETLOGFONT"), WM_CHOOSEFONT_SETLOGFONT },
    { _T("WM_CLEAR"), WM_CLEAR },
    { _T("WM_CLOSE"), WM_CLOSE },
    { _T("WM_COMMAND"), WM_COMMAND },
    { _T("WM_COMMANDHELP"), 0x0365 }, // WM_COMMANDHELP
    { _T("WM_COMPACTING"), WM_COMPACTING },
    { _T("WM_COMPAREITEM"), WM_COMPAREITEM },
    { _T("WM_CONTEXTMENU"), WM_CONTEXTMENU },
    //{ _T("WM_CONVERTREQUESTEX"), WM_CONVERTREQUESTEX
    { _T("WM_COPY"), WM_COPY },
    { _T("WM_COPYDATA"), WM_COPYDATA },
    { _T("WM_CREATE"), WM_CREATE },
    { _T("WM_CTLCOLORBTN"), WM_CTLCOLORBTN },
    { _T("WM_CTLCOLORDLG"), WM_CTLCOLORDLG },
    { _T("WM_CTLCOLOREDIT"), WM_CTLCOLOREDIT },
    { _T("WM_CTLCOLORLISTBOX"), WM_CTLCOLORLISTBOX },
    { _T("WM_CTLCOLORMSGBOX"), WM_CTLCOLORMSGBOX },
    { _T("WM_CTLCOLORSCROLLBAR"), WM_CTLCOLORSCROLLBAR },
    { _T("WM_CTLCOLORSTATIC"), WM_CTLCOLORSTATIC },
    //{ _T("WM_CTLINIT"), WM_CTLINIT },
    { _T("WM_CUT"), WM_CUT },
    { _T("WM_DDE_ACK"), WM_DDE_ACK },
    { _T("WM_DDE_ADVISE"), WM_DDE_ADVISE },
    { _T("WM_DDE_DATA"), WM_DDE_DATA },
    { _T("WM_DDE_EXECUTE"), WM_DDE_EXECUTE },
    { _T("WM_DDE_INITIATE"), WM_DDE_INITIATE },
    { _T("WM_DDE_POKE"), WM_DDE_POKE },
    { _T("WM_DDE_REQUEST"), WM_DDE_REQUEST },
    { _T("WM_DDE_TERMINATE"), WM_DDE_TERMINATE },
    { _T("WM_DDE_UNADVISE"), WM_DDE_UNADVISE },
    { _T("WM_DEADCHAR"), WM_DEADCHAR },
    { _T("WM_DELETEITEM"), WM_DELETEITEM },
    { _T("WM_DESTROY"), WM_DESTROY },
    { _T("WM_DESTROYCLIPBOARD"), WM_DESTROYCLIPBOARD },
    { _T("WM_DEVICECHANGE"), WM_DEVICECHANGE },
    { _T("WM_DEVMODECHANGE"), WM_DEVMODECHANGE },
    { _T("WM_DISABLEMODAL"), 0x036C }, // WM_DISABLEMODAL
    { _T("WM_DISPLAYCHANGE"), WM_DISPLAYCHANGE },
    { _T("WM_DRAWCLIPBOARD"), WM_DRAWCLIPBOARD },
    { _T("WM_DRAWITEM"), WM_DRAWITEM },
    { _T("WM_DROPFILES"), WM_DROPFILES },
    { _T("WM_ENABLE"), WM_ENABLE },
    { _T("WM_ENDSESSION"), WM_ENDSESSION },
    { _T("WM_ENTERIDLE"), WM_ENTERIDLE },
    { _T("WM_ENTERMENULOOP"), WM_ENTERMENULOOP },
    { _T("WM_ENTERSIZEMOVE"), WM_ENTERSIZEMOVE },
    { _T("WM_ERASEBKGND"), WM_ERASEBKGND },
    { _T("WM_EXITHELPMODE"), 0x0367 }, // WM_EXITHELPMODE
    { _T("WM_EXITMENULOOP"), WM_EXITMENULOOP },
    { _T("WM_EXITSIZEMOVE"), WM_EXITSIZEMOVE },
    { _T("WM_FLOATSTATUS"), 0x036D }, // WM_FLOATSTATUS
    { _T("WM_FONTCHANGE"), WM_FONTCHANGE },
    { _T("WM_GETDLGCODE"), WM_GETDLGCODE },
    { _T("WM_GETFONT"), WM_GETFONT },
    { _T("WM_GETHOTKEY"), WM_GETHOTKEY },
    { _T("WM_GETICON"), WM_GETICON },
    { _T("WM_GETMINMAXINFO"), WM_GETMINMAXINFO },
    { _T("WM_GETOBJECT"), WM_GETOBJECT },
    { _T("WM_GETTEXT"), WM_GETTEXT },
    { _T("WM_GETTEXTLENGTH"), WM_GETTEXTLENGTH },
    { _T("WM_HELP"), WM_HELP },
    { _T("WM_HELPHITTEST"), 0x0366 }, // WM_HELPHITTEST
    { _T("WM_HOTKEY"), WM_HOTKEY },
    { _T("WM_HSCROLL"), WM_HSCROLL },
    { _T("WM_HSCROLLCLIPBOARD"), WM_HSCROLLCLIPBOARD },
    { _T("WM_ICONERASEBKGND"), WM_ICONERASEBKGND },
    { _T("WM_IDLEUPDATECMDUI"), 0x0363 }, // WM_IDLEUPDATECMDUI
    { _T("WM_IME_CHAR"), WM_IME_CHAR },
    { _T("WM_IME_COMPOSITION"), WM_IME_COMPOSITION },
    { _T("WM_IME_COMPOSITIONFULL"), WM_IME_COMPOSITIONFULL },
    { _T("WM_IME_CONTROL"), WM_IME_CONTROL },
    { _T("WM_IME_ENDCOMPOSITION"), WM_IME_ENDCOMPOSITION },
    { _T("WM_IME_KEYDOWN"), WM_IME_KEYDOWN },
    { _T("WM_IME_KEYUP"), WM_IME_KEYUP },
    { _T("WM_IME_NOTIFY"), WM_IME_NOTIFY },
    { _T("WM_IME_REQUEST"), WM_IME_REQUEST },
    { _T("WM_IME_SELECT"), WM_IME_SELECT },
    { _T("WM_IME_SETCONTEXT"), WM_IME_SETCONTEXT },
    { _T("WM_IME_STARTCOMPOSITION"), WM_IME_STARTCOMPOSITION },
    { _T("WM_INITDIALOG"), WM_INITDIALOG },
    { _T("WM_INITIALUPDATE"), 0x0364 }, // WM_INITIALUPDATE
    { _T("WM_INITMENU"), WM_INITMENU },
    { _T("WM_INITMENUPOPUP"), WM_INITMENUPOPUP },
    { _T("WM_INPUT"), WM_INPUT },
    { _T("WM_INPUTLANGCHANGE"), WM_INPUTLANGCHANGE },
    { _T("WM_INPUTLANGCHANGEREQUEST"), WM_INPUTLANGCHANGEREQUEST },
    { _T("WM_KEYDOWN"), WM_KEYDOWN },
    { _T("WM_KEYUP"), WM_KEYUP },
    { _T("WM_KICKIDLE"), 0x036A }, // WM_KICKIDLE
    { _T("WM_KILLFOCUS"), WM_KILLFOCUS },
    { _T("WM_LBUTTONDBLCLK"), WM_LBUTTONDBLCLK },
    { _T("WM_LBUTTONDOWN"), WM_LBUTTONDOWN },
    { _T("WM_LBUTTONUP"), WM_LBUTTONUP },
    { _T("WM_MBUTTONDBLCLK"), WM_MBUTTONDBLCLK },
    { _T("WM_MBUTTONDOWN"), WM_MBUTTONDOWN },
    { _T("WM_MBUTTONUP"), WM_MBUTTONUP },
    { _T("WM_MDIACTIVATE"), WM_MDIACTIVATE },
    { _T("WM_MDICASCADE"), WM_MDICASCADE },
    { _T("WM_MDICREATE"), WM_MDICREATE },
    { _T("WM_MDIDESTROY"), WM_MDIDESTROY },
    { _T("WM_MDIGETACTIVE"), WM_MDIGETACTIVE },
    { _T("WM_MDIICONARRANGE"), WM_MDIICONARRANGE },
    { _T("WM_MDIMAXIMIZE"), WM_MDIMAXIMIZE },
    { _T("WM_MDINEXT"), WM_MDINEXT },
    { _T("WM_MDIREFRESHMENU"), WM_MDIREFRESHMENU },
    { _T("WM_MDIRESTORE"), WM_MDIRESTORE },
    { _T("WM_MDISETMENU"), WM_MDISETMENU },
    { _T("WM_MDITILE"), WM_MDITILE },
    { _T("WM_MEASUREITEM"), WM_MEASUREITEM },
    { _T("WM_MENUCHAR"), WM_MENUCHAR },
    { _T("WM_MENUCOMMAND"), WM_MENUCOMMAND },
    { _T("WM_MENUDRAG"), WM_MENUDRAG },
    { _T("WM_MENUGETOBJECT"), WM_MENUGETOBJECT },
    { _T("WM_MENURBUTTONUP"), WM_MENURBUTTONUP },
    { _T("WM_MENUSELECT"), WM_MENUSELECT },
    { _T("WM_MOUSEACTIVATE"), WM_MOUSEACTIVATE },
    { _T("WM_MOUSEHOVER"), WM_MOUSEHOVER },
    { _T("WM_MOUSELEAVE"), WM_MOUSELEAVE },
    { _T("WM_MOUSEMOVE"), WM_MOUSEMOVE },
    { _T("WM_MOUSEWHEEL"), WM_MOUSEWHEEL },
    { _T("WM_MOVE"), WM_MOVE },
    { _T("WM_MOVING"), WM_MOVING },
    { _T("WM_NCACTIVATE"), WM_NCACTIVATE },
    { _T("WM_NCCALCSIZE"), WM_NCCALCSIZE },
    { _T("WM_NCCREATE"), WM_NCCREATE },
    { _T("WM_NCDESTROY"), WM_NCDESTROY },
    { _T("WM_NCHITTEST"), WM_NCHITTEST },
    { _T("WM_NCLBUTTONDBLCLK"), WM_NCLBUTTONDBLCLK },
    { _T("WM_NCLBUTTONDOWN"), WM_NCLBUTTONDOWN },
    { _T("WM_NCLBUTTONUP"), WM_NCLBUTTONUP },
    { _T("WM_NCMBUTTONDBLCLK"), WM_NCMBUTTONDBLCLK },
    { _T("WM_NCMBUTTONDOWN"), WM_NCMBUTTONDOWN },
    { _T("WM_NCMBUTTONUP"), WM_NCMBUTTONUP },
    { _T("WM_NCMOUSEHOVER"), WM_NCMOUSEHOVER },
    { _T("WM_NCMOUSELEAVE"), WM_NCMOUSELEAVE },
    { _T("WM_NCMOUSEMOVE"), WM_NCMOUSEMOVE },
    { _T("WM_NCPAINT"), WM_NCPAINT },
    { _T("WM_NCRBUTTONDBLCLK"), WM_NCRBUTTONDBLCLK },
    { _T("WM_NCRBUTTONDOWN"), WM_NCRBUTTONDOWN },
    { _T("WM_NCRBUTTONUP"), WM_NCRBUTTONUP },
    { _T("WM_NCXBUTTONDBLCLK"), WM_NCXBUTTONDBLCLK },
    { _T("WM_NCXBUTTONDOWN"), WM_NCXBUTTONDOWN },
    { _T("WM_NCXBUTTONUP"), WM_NCXBUTTONUP },
    { _T("WM_NEXTDLGCTL"), WM_NEXTDLGCTL },
    { _T("WM_NEXTMENU"), WM_NEXTMENU },
    { _T("WM_NOTIFY"), WM_NOTIFY },
    { _T("WM_NOTIFYFORMAT"), WM_NOTIFYFORMAT },
    { _T("WM_NULL"), WM_NULL },
    { _T("WM_PAINT"), WM_PAINT },
    { _T("WM_PAINTCLIPBOARD"), WM_PAINTCLIPBOARD },
    { _T("WM_PAINTICON"), WM_PAINTICON },
    { _T("WM_PALETTECHANGED"), WM_PALETTECHANGED },
    { _T("WM_PALETTEISCHANGING"), WM_PALETTEISCHANGING },
    { _T("WM_PARENTNOTIFY"), WM_PARENTNOTIFY },
    { _T("WM_PASTE"), WM_PASTE },
    //     { _T("WM_PENCTL"), WM_PENCTL },
    //     { _T("WM_PENEVENT"), WM_PENEVENT },
    //     { _T("WM_PENMISC"), WM_PENMISC },
    //     { _T("WM_PENMISCINFO"), WM_PENMISCINFO },
    { _T("WM_POPMESSAGESTRING"), 0x0375 }, // WM_POPMESSAGESTRING
    { _T("WM_POWER"), WM_POWER },
    { _T("WM_POWERBROADCAST"), WM_POWERBROADCAST },
    { _T("WM_PRINT"), WM_PRINT },
    { _T("WM_PRINTCLIENT"), WM_PRINTCLIENT },
    { _T("WM_PSD_ENVSTAMPRECT"), WM_PSD_ENVSTAMPRECT },
    { _T("WM_PSD_FULLPAGERECT"), WM_PSD_FULLPAGERECT },
    { _T("WM_PSD_GREEKTEXTRECT"), WM_PSD_GREEKTEXTRECT },
    { _T("WM_PSD_MARGINRECT"), WM_PSD_MARGINRECT },
    { _T("WM_PSD_MINMARGINRECT"), WM_PSD_MINMARGINRECT },
    { _T("WM_PSD_PAGESETUPDLG"), WM_PSD_PAGESETUPDLG },
    { _T("WM_PSD_YAFULLPAGERECT"), WM_PSD_YAFULLPAGERECT },
    { _T("WM_QUERYAFXWNDPROC"), 0x0360 }, // WM_QUERYAFXWNDPROC
    { _T("WM_QUERYCENTERWND"), 0x036B }, // WM_QUERYCENTERWND
    { _T("WM_QUERYDRAGICON"), WM_QUERYDRAGICON },
    { _T("WM_QUERYENDSESSION"), WM_QUERYENDSESSION },
    { _T("WM_QUERYNEWPALETTE"), WM_QUERYNEWPALETTE },
    { _T("WM_QUERYOPEN"), WM_QUERYOPEN },
    { _T("WM_QUERYUISTATE"), WM_QUERYUISTATE },
    { _T("WM_QUEUE_SENTINEL"), 0x0379 }, // WM_QUEUE_SENTINEL
    { _T("WM_QUEUESYNC"), WM_QUEUESYNC },
    { _T("WM_QUIT"), WM_QUIT },
    { _T("WM_RBUTTONDBLCLK"), WM_RBUTTONDBLCLK },
    { _T("WM_RBUTTONDOWN"), WM_RBUTTONDOWN },
    { _T("WM_RBUTTONUP"), WM_RBUTTONUP },
    { _T("WM_RECALCPARENT"), 0x0368 }, // WM_RECALCPARENT
    { _T("WM_RENDERALLFORMATS"), WM_RENDERALLFORMATS },
    { _T("WM_RENDERFORMAT"), WM_RENDERFORMAT },
    { _T("WM_SETCURSOR"), WM_SETCURSOR },
    { _T("WM_SETFOCUS"), WM_SETFOCUS },
    { _T("WM_SETFONT"), WM_SETFONT },
    { _T("WM_SETHOTKEY"), WM_SETHOTKEY },
    { _T("WM_SETICON"), WM_SETICON },
    { _T("WM_SETMESSAGESTRING"), 0x0362 }, // WM_SETMESSAGESTRING
    { _T("WM_SETREDRAW"), WM_SETREDRAW },
    { _T("WM_SETTEXT"), WM_SETTEXT },
    { _T("WM_SETTINGCHANGE"), WM_SETTINGCHANGE },
    { _T("WM_SHOWWINDOW"), WM_SHOWWINDOW },
    { _T("WM_SIZE"), WM_SIZE },
    { _T("WM_SIZECHILD"), 0x0369 }, // WM_SIZECHILD
    { _T("WM_SIZECLIPBOARD"), WM_SIZECLIPBOARD },
    { _T("WM_SIZING"), WM_SIZING },
    { _T("WM_SIZEPARENT"), 0x0361 }, // WM_SIZEPARENT
    { _T("WM_SOCKET_NOTIFY"), 0x0373 }, // WM_SOCKET_NOTIFY
    { _T("WM_SOCKET_DEAD"), 0x0374 }, // WM_SOCKET_DEAD
    { _T("WM_SPOOLERSTATUS"), WM_SPOOLERSTATUS },
    { _T("WM_STYLECHANGED"), WM_STYLECHANGED },
    { _T("WM_STYLECHANGING"), WM_STYLECHANGING },
    { _T("WM_SYNCPAINT"), WM_SYNCPAINT },
    { _T("WM_SYSCHAR"), WM_SYSCHAR },
    { _T("WM_SYSCOLORCHANGE"), WM_SYSCOLORCHANGE },
    { _T("WM_SYSCOMMAND"), WM_SYSCOMMAND },
    { _T("WM_SYSDEADCHAR"), WM_SYSDEADCHAR },
    { _T("WM_SYSKEYDOWN"), WM_SYSKEYDOWN },
    { _T("WM_SYSKEYUP"), WM_SYSKEYUP },
    { _T("WM_TCARD"), WM_TCARD },
    { _T("WM_THEMECHANGED"), WM_THEMECHANGED },
    { _T("WM_TIMECHANGE"), WM_TIMECHANGE },
    { _T("WM_TIMER"), WM_TIMER },
    { _T("WM_UNDO"), WM_UNDO },
    { _T("WM_UNICHAR"), WM_UNICHAR },
    { _T("WM_UNINITMENUPOPUP"), WM_UNINITMENUPOPUP },
    { _T("WM_UPDATEUISTATE"), WM_UPDATEUISTATE },
    { _T("WM_USERCHANGED"), WM_USERCHANGED },
    { _T("WM_VKEYTOITEM"), WM_VKEYTOITEM },
    { _T("WM_VSCROLL"), WM_VSCROLL },
    { _T("WM_VSCROLLCLIPBOARD"), WM_VSCROLLCLIPBOARD },
    { _T("WM_WINDOWPOSCHANGED"), WM_WINDOWPOSCHANGED },
    { _T("WM_WINDOWPOSCHANGING"), WM_WINDOWPOSCHANGING },
    { _T("WM_WTSSESSION_CHANGE"), WM_WTSSESSION_CHANGE },
    { _T("WM_XBUTTONDBLCLK"), WM_XBUTTONDBLCLK },
    { _T("WM_XBUTTONDOWN"), WM_XBUTTONDOWN },
    { _T("WM_XBUTTONUP"), WM_XBUTTONUP },
};

static DWORD s_nWMInfoCount = sizeof(s_vWMInfoList) / sizeof(WMInfo);

CDlgWindowOp::CDlgWindowOp()
    : CLayout(IDD)
    , CUIControl(this)
{
    GetFramework()->RegisterComponent(COMPONENT_UI_DLG_WINDOW_OP, this);

    CString strWMInfo;
    for(DWORD i = 0; i < s_nWMInfoCount; ++i) {
        strWMInfo.Format(_T("%s [0x%x]"), s_vWMInfoList[i].m_pWMInfo, s_vWMInfoList[i].m_nMsg);
        m_vWindowMessages[strWMInfo] = s_vWMInfoList[i].m_nMsg;
    }
}

CDlgWindowOp::~CDlgWindowOp()
{
    GetFramework()->UnregisterComponent(COMPONENT_UI_DLG_WINDOW_OP);
}

LRESULT
CDlgWindowOp::OnInitDialog(HWND hWnd, LPARAM lInitData)
{
    m_oComboMessages.SubclassWindow(GetDlgItem(IDC_COMBO_WI_WINDOW_MESSAGE));
    WMList::iterator oWMIt = m_vWindowMessages.begin();
    while(oWMIt != m_vWindowMessages.end()) {
        m_oComboMessages.AddItem(oWMIt->first, -1, -1, 0, (LPARAM)oWMIt->second);
        ++oWMIt;
    }

    m_oComboMessages.TakeSnapshot();

    m_oEditWParam = GetDlgItem(IDC_EDIT_WI_WPARAM);
    m_oEditWParam.SetWindowText(_T("0"));
    m_oEditLParam = GetDlgItem(IDC_EDIT_WI_LPARAM);
    m_oEditLParam.SetWindowText(_T("0"));

    m_oBtnShowWindow.SubclassWindow(GetDlgItem(IDC_BUTTON_WI_SHOW_WINDOW));
    m_oBtnShowWindow.SetDropDownMenu(IDR_MENU_WI_SHOW_WINDOW);

    m_oBtnEnableWindow.SubclassWindow(GetDlgItem(IDC_BUTTON_WI_ENABLE_WINDOW));
    m_oBtnEnableWindow.SetDropDownMenu(IDR_MENU_WI_ENABLE_WINDOW);

    m_oBtnModifyZorder.SubclassWindow(GetDlgItem(IDC_BUTTON_WI_ZORDER));
    m_oBtnModifyZorder.SetDropDownMenu(IDR_MENU_WI_ZORDER);

    m_oBtnSysCommand.SubclassWindow(GetDlgItem(IDC_BUTTON_WI_SYSCOMMAND));
    m_oBtnSysCommand.SetDropDownMenu(IDR_MENU_WI_SYSCOMMAND);

    m_oBtnSetFocus = GetDlgItem(IDC_BUTTON_WI_SET_FOCUS);
    m_oBtnSetActive = GetDlgItem(IDC_BUTTON_WI_SET_ACTIVE);
    m_oBtnSetForeground = GetDlgItem(IDC_BUTTON_WI_SET_FOREGROUND);

    ProvideHotkey();

    return TRUE;
}

VOID
CDlgWindowOp::OnShowWindow(BOOL bShow, int nStatus)
{
    SetMsgHandled(FALSE);
    return;
}


VOID
CDlgWindowOp::OnClose()
{
    SetMsgHandled(FALSE);
    DestroyWindow();
    return;
}

VOID
CDlgWindowOp::OnDestroy()
{
    SetMsgHandled(FALSE);
    return;
}

VOID
CDlgWindowOp::OnSendMessage(UINT nNotifyCode, UINT nId, HWND hCtrlWnd)
{
    SendMessageToWindow(TRUE);
    return;
}

VOID
CDlgWindowOp::OnPostMessage(UINT nNotifyCode, UINT nId, HWND hCtrlWnd)
{
    SendMessageToWindow(FALSE);
    return;
}

VOID
CDlgWindowOp::OnBtnShowWindowMenu(UINT nNotifyCode, UINT nId, HWND hWndCtrl)
{
    CWindow oWatchWindow;
    ENSURE_WATCH_WINDOW_RET_VOID(oWatchWindow);

    int nCmdShow = SW_SHOW;
    switch(nId) {
    case ID_WI_SHOW_WINDOW_SW_SHOW:  { nCmdShow = SW_SHOW; break; }
    case ID_WI_SHOW_WINDOW_SW_SHOWNORMAL:  { nCmdShow = SW_SHOWNORMAL; break; }
    case ID_WI_SHOW_WINDOW_SW_SHOWDEFAULT:  { nCmdShow = SW_SHOWDEFAULT; break; }
    case ID_WI_SHOW_WINDOW_SW_MAXIMIZE:  { nCmdShow = SW_MAXIMIZE; break; }
    case ID_WI_SHOW_WINDOW_SW_SHOWMAXIMIZED:  { nCmdShow = SW_SHOWMAXIMIZED; break; }
    case ID_WI_SHOW_WINDOW_SW_MINIMIZE:  { nCmdShow = SW_MINIMIZE; break; }
    case ID_WI_SHOW_WINDOW_SW_SHOWMINIMIZED:  { nCmdShow = SW_SHOWMINIMIZED; break; }
    case ID_WI_SHOW_WINDOW_SW_SHOWMINNOACTIVE:  { nCmdShow = SW_SHOWMINNOACTIVE; break; }
    case ID_WI_SHOW_WINDOW_SW_FORCEMINIMIZE:  { nCmdShow = SW_FORCEMINIMIZE; break; }
    case ID_WI_SHOW_WINDOW_SW_RESTORE:  { nCmdShow = SW_RESTORE; break; }
    case ID_WI_SHOW_WINDOW_SW_SHOWNA:  { nCmdShow = SW_SHOWNA; break; }
    case ID_WI_SHOW_WINDOW_SW_SHOWNOACTIVATE:  { nCmdShow = SW_SHOWNOACTIVATE; break; }
    case ID_WI_SHOW_WINDOW_SW_HIDE:  { nCmdShow = SW_HIDE; break; }
    }

    oWatchWindow.ShowWindow(nCmdShow);

    RefreshAllWindowInfo();

    return;
}

VOID
CDlgWindowOp::OnBtnEnableWindow(UINT nNotifyCode, UINT nId, HWND hWndCtrl)
{
    CWindow oWatchWindow;
    ENSURE_WATCH_WINDOW_RET_VOID(oWatchWindow);

    BOOL bEnable = FALSE;
    switch (nId) {
    case ID_WI_ENABLE_WINDOW_TRUE:
        bEnable = TRUE;
        break;
    case ID_WI_ENABLE_WINDOW_FALSE:
        bEnable = FALSE;
        break;
    }

    oWatchWindow.EnableWindow(bEnable);

    return;
}

VOID
CDlgWindowOp::OnBtnZorderMenu(UINT nNotifyCode, UINT nId, HWND hWndCtrl)
{
    CWindow oWatchWindow;
    ENSURE_WATCH_WINDOW_RET_VOID(oWatchWindow);

    HWND nInsertWnd = NULL;
    switch(nId) {
    case ID_WI_ZORDER_TOPMOST: { nInsertWnd = HWND_TOPMOST; break; }
    case ID_WI_ZORDER_TOP: { nInsertWnd = HWND_TOP; break; }
    case ID_WI_ZORDER_BOTTOM: { nInsertWnd = HWND_BOTTOM; break; }
    }

    oWatchWindow.SetWindowPos(nInsertWnd, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE);

    RefreshAllWindowInfo();

    return;
}

VOID
CDlgWindowOp::OnBtnSysCommandMenu(UINT nNotifyCode, UINT nId, HWND hWndCtrl)
{
    CWindow oWatchWindow;
    ENSURE_WATCH_WINDOW_RET_VOID(oWatchWindow);

    LPARAM lParam = 0;
    switch(nId) {
    case ID_WI_SYSCOMMAND_SC_CLOSE:  { lParam = SC_CLOSE; break; }
    case ID_WI_SYSCOMMAND_SC_CONTEXTHELP:  { lParam = SC_CONTEXTHELP; break; }
    case ID_WI_SYSCOMMAND_SC_DEFAULT:  { lParam = SC_DEFAULT; break; }
    case ID_WI_SYSCOMMAND_SC_HOTKEY:  { lParam = SC_HOTKEY; break; }
    case ID_WI_SYSCOMMAND_SC_HSCROLL:  { lParam = SC_HSCROLL; break; }
    case ID_WI_SYSCOMMAND_SC_KEYMENU:  { lParam = SC_KEYMENU; break; }
    case ID_WI_SYSCOMMAND_SC_MAXIMIZE:  { lParam = SC_MAXIMIZE; break; }
    case ID_WI_SYSCOMMAND_SC_MINIMIZE:  { lParam = SC_MINIMIZE; break; }
    case ID_WI_SYSCOMMAND_SC_MONITORPOWER:  { lParam = SC_MONITORPOWER; break; }
    case ID_WI_SYSCOMMAND_SC_MOUSEMENU:  { lParam = SC_MOUSEMENU; break; }
    case ID_WI_SYSCOMMAND_SC_MOVE:  { lParam = SC_MOVE; break; }
    case ID_WI_SYSCOMMAND_SC_NEXTWINDOW:  { lParam = SC_NEXTWINDOW; break; }
    case ID_WI_SYSCOMMAND_SC_PREVWINDOW:  { lParam = SC_PREVWINDOW; break; }
    case ID_WI_SYSCOMMAND_SC_RESTORE:  { lParam = SC_RESTORE; break; }
    case ID_WI_SYSCOMMAND_SC_SCREENSAVE:  { lParam = SC_SCREENSAVE; break; }
    case ID_WI_SYSCOMMAND_SC_SIZE:  { lParam = SC_SIZE; break; }
    case ID_WI_SYSCOMMAND_SC_TASKLIST:  { lParam = SC_TASKLIST; break; }
    case ID_WI_SYSCOMMAND_SC_VSCROLL:  { lParam = SC_VSCROLL; break; }
    }

    oWatchWindow.SendMessage(WM_SYSCOMMAND, lParam, 0);

    RefreshAllWindowInfo();

    return;
}

VOID
CDlgWindowOp::OnBtnSetFocus(UINT nNotifyCode, UINT nId, HWND hWndCtrl)
{
    CWindow oWatchWindow;
    ENSURE_WATCH_WINDOW_RET_VOID(oWatchWindow);

    {
        ScopedThreadAttach oThreadAttach(oWatchWindow.GetWindowThreadID(), GetCurrentThreadId());
        oWatchWindow.SetFocus();
    }

    RefreshAllWindowInfo();

    return;
}

VOID
CDlgWindowOp::OnBtnSetActive(UINT nNotifyCode, UINT nId, HWND hWndCtrl)
{
    CWindow oWatchWindow;
    ENSURE_WATCH_WINDOW_RET_VOID(oWatchWindow);

    {
        ScopedThreadAttach oThreadAttach(oWatchWindow.GetWindowThreadID(), GetCurrentThreadId());
        oWatchWindow.SetActiveWindow();
    }

    RefreshAllWindowInfo();

    return;
}

VOID
CDlgWindowOp::OnBtnSetForeground(UINT nNotifyCode, UINT nId, HWND hWndCtrl)
{
    CWindow oWatchWindow;
    ENSURE_WATCH_WINDOW_RET_VOID(oWatchWindow);

    {
        ScopedThreadAttach oThreadAttach(oWatchWindow.GetWindowThreadID(), GetCurrentThreadId());
        oWatchWindow.SetActiveWindow();
    }

    RefreshAllWindowInfo();

    return;
}

VOID
CDlgWindowOp::OnBtnParseWaitChain(UINT nNotifyCode, UINT nId, HWND hWndCtrl)
{
    CWindow oWatchWindow;
    ENSURE_WATCH_WINDOW_RET_VOID(oWatchWindow);

    CComPtr<IWaitChain> pWC;
    if(FAILED(MirrorCreateObject(MODULE_PROCESS, __uuidof(IWaitChain), (void **)&pWC)) || NULL == pWC) {
        return;
    }
    
    pWC->AnalyzeThread(oWatchWindow.GetWindowThreadID(), NULL);

    return;
}

VOID
CDlgWindowOp::ProvideHotkey()
{
    static HotkeyHandlerData s_vHandlers[] = {
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SEND_MESSAGE, m_hWnd, WM_COMMAND, (WPARAM)IDC_BUTTON_WI_SEND_MESSAGE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_SHOW, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_SHOW, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_SHOWNORMAL, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_SHOWNORMAL, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_SHOWDEFAULT, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_SHOWDEFAULT, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_MAXIMIZE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_MAXIMIZE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_SHOWMAXIMIZED, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_SHOWMAXIMIZED, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_MINIMIZE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_MINIMIZE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_SHOWMINIMIZED, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_SHOWMINIMIZED, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_SHOWMINNOACTIVE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_SHOWMINNOACTIVE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_FORCEMINIMIZE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_FORCEMINIMIZE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_RESTORE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_RESTORE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_SHOWNA, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_SHOWNA, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_SHOWNOACTIVATE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_SHOWNOACTIVATE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SHOW_WINDOW_SW_HIDE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SHOW_WINDOW_SW_HIDE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_ENABLE_WINDOW_TRUE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_ENABLE_WINDOW_TRUE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_ENABLE_WINDOW_FALSE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_ENABLE_WINDOW_FALSE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_ZORDER_HWND_TOPMOST, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_ZORDER_TOPMOST, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_ZORDER_HWND_TOP, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_ZORDER_TOP, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_ZORDER_HWND_BOTTOM, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_ZORDER_BOTTOM, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_CLOSE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_CLOSE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_CONTEXTHELP, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_CONTEXTHELP, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_DEFAULT, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_DEFAULT, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_HOTKEY, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_HOTKEY, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_HSCROLL, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_HSCROLL, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_KEYMENU, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_KEYMENU, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_MAXIMIZE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_MAXIMIZE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_MINIMIZE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_MINIMIZE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_MONITORPOWER, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_MONITORPOWER, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_MOUSEMENU, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_MOUSEMENU, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_MOVE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_MOVE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_NEXTWINDOW, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_NEXTWINDOW, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_PREVWINDOW, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_PREVWINDOW, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_RESTORE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_RESTORE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_SCREENSAVE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_SCREENSAVE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_SIZE, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_SIZE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_TASKLIST, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_TASKLIST, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SYSCOMMAND_SC_VSCROLL, m_hWnd, WM_COMMAND, (WPARAM)ID_WI_SYSCOMMAND_SC_VSCROLL, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SET_FOCUS, m_hWnd, WM_COMMAND, (WPARAM)IDC_BUTTON_WI_SET_FOCUS, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SET_ACTIVE, m_hWnd, WM_COMMAND, (WPARAM)IDC_BUTTON_WI_SET_ACTIVE, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_SET_FOREGROUND, m_hWnd, WM_COMMAND, (WPARAM)IDC_BUTTON_WI_SET_FOREGROUND, 0 },
        { HOTKEY_SECTION_WINDOW_OP, HOTKEY_NAME_WINDOW_OP_PARSE_WAIT_CHAIN, m_hWnd, WM_COMMAND, (WPARAM)IDC_BUTTON_WI_PARSE_WAIT_CHAIN, 0 },
    };

    static DWORD s_nHandlerNum = sizeof(s_vHandlers) / sizeof(HotkeyHandlerData);

    ProvideHotkeyHandler(s_vHandlers, s_nHandlerNum);

    return;
}

VOID
CDlgWindowOp::SendMessageToWindow(BOOL bSync)
{
    HWND hWatchWindow = GetWatchWindow();
    if(NULL == hWatchWindow || !::IsWindow(hWatchWindow)) {
        return;
    }

    DWORD nMsg = 0;
    int nCurSel = m_oComboMessages.GetCurSel();
    if(nCurSel >= 0) {
        nMsg = (DWORD)m_oComboMessages.GetItemData(nCurSel);
    } else {
        CString strInput;
        m_oComboMessages.GetWindowText(strInput);
        nMsg = findIntInString(strInput);
    }

    CString strWParam, strLParam;
    m_oEditWParam.GetWindowText(strWParam);
    m_oEditLParam.GetWindowText(strLParam);

    WPARAM wParam = (WPARAM)findIntInString(strWParam);
    LPARAM lParam = (LPARAM)findIntInString(strLParam);

    LRESULT nRet = FALSE;
    if(bSync) {
        nRet = ::SendMessage(hWatchWindow, nMsg, wParam, lParam);
    } else {
        nRet = ::PostMessage(hWatchWindow, nMsg, wParam, lParam);
    }

    DWORD nErrCode = ::GetLastError();

    MLOG_INFO("Window", "发送消息结束：Message = %lu(0x%x)，wParam = %lu(0x%x)，lParam = %lu(0x%x)，Ret = %lu，ErrCode = %lu。",
        nMsg, nMsg, wParam, wParam, lParam, lParam, nRet, nErrCode);

    RefreshAllWindowInfo();
}
